// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'comments',

  extras: $ => [
    /[\t\n\r ]+/,
    $.line,
    $.block
  ],

  rules: {
    file: $ => field('body', $.list),

    list: $ => seq('[', optional(seq(sepBy1(',', field('elt', $.item)), optional(','))), ']'),

    item: $ => seq(
      field('head', choice($.name, $.number, $.list)),
      repeat(field('field', $.field))
    ),

    field: $ => seq(field('dot', '.'), field('tail', choice($.name, $.number))),

    name: $ => /[a-z]+/,

    number: $ => /[0-9]+(?:\.[0-9]+)?/,

    line: $ => /\/\/[^\n]*/,

    block: $ => /\/\*(?:[^*]|\*+[^*\/])*\*+\//
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
