; Generated by lingo from the grammar. Do not edit by hand.
;
; The first pattern that matches a node wins, so what is written for one
; position comes before what is written for the token itself.

; every occurrence of a token
"module" @keyword
"import" @keyword
"def" @keyword
"val" @keyword
"var" @keyword
"type" @keyword
"record" @keyword
"interface" @keyword
"effect" @keyword
"namespace" @keyword
"if" @keyword
"else" @keyword
"while" @keyword
"try" @keyword
"with" @keyword
"case" @keyword
"match" @keyword
"do" @keyword
"return" @keyword
"box" @keyword
"unbox" @keyword
"fn" @keyword
"at" @keyword
"and" @operator
"resume" @keyword
"true" @keyword
"false" @keyword
"{" @punctuation.bracket
"}" @punctuation.bracket
"(" @punctuation.bracket
")" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
"," @punctuation.delimiter
";" @punctuation.delimiter
":" @punctuation.delimiter
"." @punctuation.delimiter
"::" @punctuation.delimiter
"->" @punctuation.delimiter
"=>" @punctuation.delimiter
"=" @punctuation.delimiter
"==" @operator
"!=" @operator
"<" @operator
">" @operator
"<=" @operator
">=" @operator
"+" @operator
"-" @operator
"*" @operator
"/" @operator
"|" @punctuation.delimiter
"!" @operator
(ident) @variable
(int) @number
(string) @string
(doc_comment) @comment
(line_comment) @comment
(block_comment) @comment

