// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'effekt',

  extras: $ => [
    /[\t\n\r ]+/,
    $.line_comment,
    $.block_comment
  ],

  word: $ => $.ident,

  rules: {
    file: $ => seq(optional(field('header', $.module)), repeat(field('item', $.item))),

    module: $ => seq(field('kw', 'module'), field('path', $.path), field('semi', ';')),

    doc_block: $ => repeat1(field('line', $.doc_comment)),

    item: $ => seq(optional(field('doc', $.doc_block)), field('def', $.definition)),

    definition: $ => field(
      'kind',
      choice(
        $.import,
        $.def,
        $.val_def,
        $.var_def,
        $.type_def,
        $.record,
        $.interface,
        $.effect,
        $.namespace
      )
    ),

    path: $ => seq(field('first', $.ident), repeat(field('rest', $.path_segment))),

    path_segment: $ => seq(field('sep', '::'), field('name', $.ident)),

    import: $ => seq(field('kw', 'import'), field('path', $.path), field('semi', ';')),

    param: $ => seq(field('name', $.ident), optional(field('ann', $.type_ann))),

    type_ann: $ => seq(field('colon', ':'), field('ty', $.type)),

    params: $ => seq(
      '(',
      optional(seq(sepBy1(',', field('param', $.param)), optional(','))),
      ')'
    ),

    def: $ => seq(
      field('kw', 'def'),
      field('name', $.ident),
      optional(field('params', $.params)),
      optional(field('ret', $.type_ann)),
      field('eq', '='),
      field('body', $._expr),
      field('semi', ';')
    ),

    val_def: $ => seq(
      field('kw', 'val'),
      field('name', $.ident),
      optional(field('ann', $.type_ann)),
      field('eq', '='),
      field('value', $._expr),
      field('semi', ';')
    ),

    var_def: $ => seq(
      field('kw', 'var'),
      field('name', $.ident),
      optional(field('ann', $.type_ann)),
      field('eq', '='),
      field('value', $._expr),
      field('semi', ';')
    ),

    type_def: $ => seq(
      field('kw', 'type'),
      field('name', $.ident),
      field('eq', '='),
      field('ty', $.type),
      field('semi', ';')
    ),

    record: $ => seq(field('kw', 'record'), field('name', $.ident), field('fields', $.params)),

    operation: $ => seq(
      optional(field('doc', $.doc_block)),
      field('kw', 'def'),
      field('name', $.ident),
      field('params', $.params),
      optional(field('ret', $.type_ann))
    ),

    interface_body: $ => seq('{', repeat(field('op', $.operation)), '}'),

    interface: $ => seq(
      field('kw', 'interface'),
      field('name', $.ident),
      field('body', $.interface_body)
    ),

    effect: $ => seq(
      field('kw', 'effect'),
      field('name', $.ident),
      field('params', $.params),
      optional(field('ret', $.type_ann)),
      field('semi', ';')
    ),

    namespace_body: $ => seq('{', repeat(field('item', $.item)), '}'),

    namespace: $ => seq(
      field('kw', 'namespace'),
      field('name', $.ident),
      field('body', $.namespace_body)
    ),

    type: $ => seq(field('from', $.boxed_type), optional(field('to_', $.type_arrow))),

    type_arrow: $ => seq(field('arrow', '->'), field('result', $.boxed_type)),

    boxed_type: $ => seq(
      field('base', $.atomic_type),
      optional(field('capture', $.capture_set))
    ),

    capture_set: $ => seq(field('kw', 'at'), field('set', $.capture_list)),

    capture_list: $ => seq('{', optional(sepBy1(',', field('name', $.ident))), '}'),

    atomic_type: $ => seq(field('name', $.ident), optional(field('args', $.type_args))),

    type_args: $ => seq('[', sepBy1(',', field('arg', $.type)), ']'),

    block: $ => seq('{', repeat(field('stmt', $.stmt)), '}'),

    stmt: $ => field('kind', choice($.val_def, $.var_def, $.def, $.expr_stmt)),

    expr_stmt: $ => seq(field('expr', $._expr), field('semi', ';')),

    if: $ => prec.right(
      1,
      seq(
        field('kw', 'if'),
        field('cond', $.paren),
        field('then_', $._expr),
        optional(field('else_', $.else))
      )
    ),

    else: $ => seq(field('kw', 'else'), field('body', $._expr)),

    while: $ => seq(field('kw', 'while'), field('cond', $.paren), field('body', $._expr)),

    paren: $ => seq('(', field('inner', $._expr), ')'),

    do: $ => seq(field('kw', 'do'), field('name', $.ident), field('args', $.args)),

    args: $ => seq('(', optional(seq(sepBy1(',', field('arg', $._expr)), optional(','))), ')'),

    return: $ => seq(field('kw', 'return'), field('value', $._expr)),

    resume: $ => seq(field('kw', 'resume'), field('args', $.args)),

    box: $ => seq(field('kw', 'box'), field('value', $._expr)),

    unbox: $ => seq(field('kw', 'unbox'), field('value', $._expr)),

    fn: $ => seq(
      field('kw', 'fn'),
      field('params', $.params),
      field('arrow', '=>'),
      field('body', $._expr)
    ),

    try: $ => seq(
      field('kw', 'try'),
      field('body', $.block),
      repeat1(field('handler', $.handler))
    ),

    handler: $ => seq(
      field('kw', 'with'),
      field('name', $.ident),
      field('body', $.handler_body)
    ),

    handler_body: $ => seq('{', repeat(field('clause', $.clause)), '}'),

    clause: $ => seq(
      field('kw', 'def'),
      field('name', $.ident),
      field('params', $.params),
      field('eq', '='),
      field('body', $._expr)
    ),

    match: $ => seq(
      field('kw', 'match'),
      field('scrutinee', $.paren),
      field('body', $.match_body)
    ),

    match_body: $ => seq('{', repeat(field('arm', $.match_arm)), '}'),

    match_arm: $ => seq(
      field('kw', 'case'),
      field('pat', $.pattern),
      repeat(field('extra', $.alt_pattern)),
      optional(field('guard', $.guard)),
      field('arrow', '=>'),
      field('body', $._expr)
    ),

    alt_pattern: $ => seq(field('bar', '|'), field('pat', $.pattern)),

    guard: $ => seq(field('kw', 'and'), field('cond', $._expr)),

    pattern: $ => seq(
      field('head', choice($.ident, $.int, $.string)),
      optional(field('args', $.pattern_args))
    ),

    pattern_args: $ => seq('(', optional(sepBy1(',', field('arg', $.pattern))), ')'),

    hole: $ => seq('<{', repeat(field('stmt', $.stmt)), '}>'),

    expr: $ => field('atom', choice($.int, $.string, $.ident, 'true', 'false')),

    _expr: $ => choice(
      $.expr,
      $.expr_bin,
      $.expr_prefix,
      $.expr_postfix_select,
      $.expr_postfix_typed,
      $.expr_postfix_call,
      $.expr_postfix_block,
      $.block,
      $.paren,
      $.hole,
      $.if,
      $.while,
      $.try,
      $.match,
      $.do,
      $.return,
      $.resume,
      $.box,
      $.unbox,
      $.fn
    ),

    expr_bin: $ => choice(
      prec.left(5, seq(field('lhs', $._expr), field('op', 'and'), field('rhs', $._expr))),
      prec.left(10, seq(field('lhs', $._expr), field('op', '=='), field('rhs', $._expr))),
      prec.left(10, seq(field('lhs', $._expr), field('op', '!='), field('rhs', $._expr))),
      prec.left(15, seq(field('lhs', $._expr), field('op', '<'), field('rhs', $._expr))),
      prec.left(15, seq(field('lhs', $._expr), field('op', '>'), field('rhs', $._expr))),
      prec.left(15, seq(field('lhs', $._expr), field('op', '<='), field('rhs', $._expr))),
      prec.left(15, seq(field('lhs', $._expr), field('op', '>='), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '+'), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '-'), field('rhs', $._expr))),
      prec.left(30, seq(field('lhs', $._expr), field('op', '*'), field('rhs', $._expr))),
      prec.left(30, seq(field('lhs', $._expr), field('op', '/'), field('rhs', $._expr)))
    ),

    expr_prefix: $ => choice(
      prec.right(70, seq(field('op', '!'), field('operand', $._expr))),
      prec.right(70, seq(field('op', '-'), field('operand', $._expr)))
    ),

    expr_postfix_select: $ => prec.left(
      90,
      seq(field('operand', $._expr), field('op', '.'), field('rhs', $.ident))
    ),

    expr_postfix_typed: $ => prec.left(
      90,
      seq(field('operand', $._expr), '[', field('body', $.type), ']')
    ),

    expr_postfix_call: $ => prec.left(
      90,
      seq(
        field('operand', $._expr),
        '(',
        optional(seq(sepBy1(',', field('args', $._expr)), optional(','))),
        ')'
      )
    ),

    expr_postfix_block: $ => prec.left(
      90,
      seq(field('operand', $._expr), '{', field('body', $.stmt), '}')
    ),

    ident: $ => /[A-Z_a-z][0-9A-Z_a-z]*/,

    int: $ => /[0-9]+/,

    string: $ => /"(?:[^"\\]|\\[\s\S])*"/,

    doc_comment: $ => /\/\/\/[^\n]*/,

    line_comment: $ => /\/\/[^\n\/][^\n]*|\/\//,

    block_comment: $ => /\/\*(?:[^*]|\*+[^*\/])*\*+\//
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
