; Generated by lingo from the grammar. Do not edit by hand.
;
; A scope holds the names introduced inside it. tree-sitter's locals
; runtime walks the tree, keeps a stack of the scopes, and matches each
; reference to the nearest enclosing definition of the same text.

; a production that opens a scope
(def) @local.scope
(record) @local.scope
(operation) @local.scope
(interface) @local.scope
(effect) @local.scope
(namespace) @local.scope
(block) @local.scope
(fn) @local.scope
(clause) @local.scope

; a child position that introduces a name
(param name: (ident) @local.definition)
(def name: (ident) @local.definition)
(val_def name: (ident) @local.definition)
(var_def name: (ident) @local.definition)
(type_def name: (ident) @local.definition)
(record name: (ident) @local.definition)
(operation name: (ident) @local.definition)
(interface name: (ident) @local.definition)
(effect name: (ident) @local.definition)
(namespace name: (ident) @local.definition)

; every identifier. Where a definition above matches the same node,
; tree-sitter takes that more specific capture.
(ident) @local.reference

