; Generated by lingo from the grammar. Do not edit by hand.
;
; A rule framed by a matched pair is a fold region.

(params) @fold
(interface_body) @fold
(namespace_body) @fold
(capture_list) @fold
(type_args) @fold
(block) @fold
(paren) @fold
(args) @fold
(handler_body) @fold
(match_body) @fold
(pattern_args) @fold
(hole) @fold
(expr_postfix_typed) @fold
(expr_postfix_call) @fold
(expr_postfix_block) @fold
