// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'json',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  rules: {
    file: $ => field('value', $.value),

    value: $ => field(
      'kind',
      choice('true', 'false', 'null', $.number, $.string, $.object, $.array)
    ),

    member: $ => seq(field('key', $.string), field('colon', ':'), field('value', $.value)),

    object: $ => seq('{', optional(sepBy1(',', field('member', $.member))), '}'),

    array: $ => seq('[', optional(sepBy1(',', field('elt', $.value))), ']'),

    number: $ => /-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[Ee][+\-]?[0-9]+)?/,

    string: $ => /"(?:[^"\\]|\\[\s\S])*"/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
