; Generated by lingo from the grammar. Do not edit by hand.
;
; The last pattern that matches a node wins, so what is written for the
; token itself comes before what is written for one position.

; every occurrence of a token
"true" @constant.builtin
"false" @constant.builtin
"null" @constant.builtin
"{" @punctuation.bracket
"}" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
"," @punctuation.delimiter
":" @punctuation.delimiter
(number) @number
(string) @string

