; Generated by lingo from the grammar. Do not edit by hand.
;
; A rule framed by a matched pair is a fold region.

(type_group) @fold
(data_body) @fold
(ctor_payload) @fold
(list) @fold
(expr_postfix_call) @fold
(expr_postfix_block) @fold
