// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'ml',

  extras: $ => [
    /[\t\n\r ]+/,
    $.comment
  ],

  word: $ => $.ident,

  rules: {
    source_file: $ => choice($.file, $.sig),

    file: $ => repeat(field('item', $.decl)),

    decl: $ => field('kind', choice($.import, $.type_decl, $.data_decl, $.let_decl)),

    sig: $ => repeat(field('item', $.sig_item)),

    sig_item: $ => field('kind', choice($.type_decl, $.val_decl)),

    val_decl: $ => seq(
      field('kw', 'val'),
      field('name', $.ident),
      field('colon', ':'),
      field('ty', $._type),
      field('semi', ';')
    ),

    import: $ => seq(field('kw', 'import'), field('path', $.path), field('semi', ';')),

    path: $ => seq(field('head', $.ident), repeat(field('rest', $.path_seg))),

    path_seg: $ => seq(field('dot', '.'), field('name', $.ident)),

    type_decl: $ => seq(
      field('kw', 'type'),
      field('name', $.ident),
      field('eq', '='),
      field('ty', $._type),
      field('semi', ';')
    ),

    type_group: $ => seq('(', field('ty', $._type), ')'),

    data_decl: $ => seq(field('kw', 'data'), field('name', $.ident), field('body', $.data_body)),

    data_body: $ => seq(
      '{',
      seq(optional('|'), optional(sepBy1('|', field('ctor', $.ctor)))),
      '}'
    ),

    ctor: $ => seq(field('name', $.ident), optional(field('payload', $.ctor_payload))),

    ctor_payload: $ => seq('(', optional(sepBy1(',', field('ty', $._type))), ')'),

    let_decl: $ => seq(
      field('kw', 'let'),
      field('name', $.ident),
      repeat(field('param', $.param)),
      field('colon', ':'),
      field('ty', $._type),
      field('eq', '='),
      field('body', $._expr),
      field('semi', ';')
    ),

    param: $ => field('kind', choice($.plain_param, $.labelled_param)),

    plain_param: $ => seq(
      field('lparen', '('),
      field('name', $.ident),
      field('colon', ':'),
      field('ty', $._type),
      field('rparen', ')')
    ),

    labelled_param: $ => seq(field('tilde', '~'), field('name', $.ident)),

    list: $ => seq('[', optional(seq(sepBy1(',', field('elem', $._expr)), optional(','))), ']'),

    if: $ => seq(
      field('kw', 'if'),
      field('cond', $._expr),
      field('then_kw', 'then'),
      field('t', $._expr),
      field('else_', $.else)
    ),

    else: $ => seq(field('kw', 'else'), field('e', $._expr)),

    stmt: $ => seq(field('e', $._expr), field('semi', ';')),

    label: $ => seq(field('tilde', '~'), field('name', $.ident), field('colon', ':')),

    arg: $ => seq(optional(field('label', $.label)), field('value', $._expr)),

    type: $ => field('atom', $.ident),

    _type: $ => choice($.type, $.type_bin, $.type_group),

    expr: $ => field('atom', choice($.int, $.ident)),

    _expr: $ => choice(
      $.expr,
      $.expr_bin,
      $.expr_prefix,
      $.expr_postfix_field,
      $.expr_postfix_call,
      $.expr_postfix_block,
      $.list,
      $.if
    ),

    type_bin: $ => choice(
      prec.right(1, seq(field('lhs', $._type), field('op', '->'), field('rhs', $._type))),
      prec.left(10, seq(field('lhs', $._type), field('op', '*'), field('rhs', $._type)))
    ),

    expr_bin: $ => choice(
      prec.left(5, seq(field('lhs', $._expr), field('op', '=='), field('rhs', $._expr))),
      prec.left(5, seq(field('lhs', $._expr), field('op', '<'), field('rhs', $._expr))),
      prec.left(10, seq(field('lhs', $._expr), field('op', '+'), field('rhs', $._expr))),
      prec.left(10, seq(field('lhs', $._expr), field('op', '-'), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '*'), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '/'), field('rhs', $._expr)))
    ),

    expr_prefix: $ => prec.right(60, seq(field('op', '!'), field('operand', $._expr))),

    expr_postfix_field: $ => prec.left(
      100,
      seq(field('operand', $._expr), field('op', '.'), field('rhs', $.ident))
    ),

    expr_postfix_call: $ => prec.left(
      100,
      seq(
        field('operand', $._expr),
        '(',
        optional(seq(sepBy1(',', field('args', $.arg)), optional(','))),
        ')'
      )
    ),

    expr_postfix_block: $ => prec.left(
      100,
      seq(field('operand', $._expr), '{', repeat(field('args', $.stmt)), '}')
    ),

    ident: $ => /[A-Z_a-z][0-9A-Z_a-z]*/,

    int: $ => /[0-9]+/,

    comment: $ => /\(\*(?:(?!\*\))[^\n])*\*\)/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
