; Generated by lingo from the grammar. Do not edit by hand.
;
; The last pattern that matches a node wins, so what is written for the
; token itself comes before what is written for one position.

; every occurrence of a token
"import" @keyword
"type" @keyword
"data" @keyword
"let" @keyword
"val" @keyword
"if" @keyword
"then" @keyword
"else" @keyword
"{" @punctuation.bracket
"}" @punctuation.bracket
"(" @punctuation.delimiter
")" @punctuation.delimiter
"[" @punctuation.bracket
"]" @punctuation.bracket
"." @punctuation.delimiter
"~" @punctuation.delimiter
"!" @operator
"," @punctuation.delimiter
";" @punctuation.delimiter
":" @punctuation.delimiter
"->" @operator
"=" @punctuation.delimiter
"|" @punctuation.delimiter
"+" @operator
"-" @operator
"*" @operator
"/" @operator
"==" @operator
"<" @operator
(ident) @variable
(int) @number
(comment) @comment

; one position of one rule
(val_decl name: (ident) @function)
(path_seg name: (ident) @variable.member)
(type_decl name: (ident) @type)
(data_decl name: (ident) @type)
(ctor name: (ident) @type)
(let_decl name: (ident) @function)
(plain_param name: (ident) @variable.parameter)
(labelled_param name: (ident) @variable.parameter)

