; Generated by lingo from the grammar. Do not edit by hand.
;
; A scope holds the names introduced inside it. tree-sitter's locals
; runtime walks the tree, keeps a stack of the scopes, and matches each
; reference to the nearest enclosing definition of the same text.

; a production that opens a scope
(data_decl) @local.scope
(let_decl) @local.scope

; a child position that introduces a name
(val_decl name: (ident) @local.definition)
(type_decl name: (ident) @local.definition)
(data_decl name: (ident) @local.definition)
(ctor name: (ident) @local.definition)
(let_decl name: (ident) @local.definition)
(plain_param name: (ident) @local.definition)
(labelled_param name: (ident) @local.definition)

; every identifier. Where a definition above matches the same node,
; tree-sitter takes that more specific capture.
(ident) @local.reference

