// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'postfix',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  rules: {
    file: $ => field('expr', $._expr),

    field: $ => field('name', $.name),

    expr: $ => field('atom', choice($.int, $.name)),

    _expr: $ => choice(
      $.expr,
      $.expr_bin,
      $.expr_postfix_try,
      $.expr_postfix_field,
      $.expr_postfix_index,
      $.expr_postfix_block,
      $.expr_postfix_call
    ),

    expr_bin: $ => prec.left(
      10,
      seq(field('lhs', $._expr), field('op', '+'), field('rhs', $._expr))
    ),

    expr_postfix_try: $ => prec.left(90, seq(field('operand', $._expr), field('op', '?'))),

    expr_postfix_field: $ => prec.left(
      90,
      seq(field('operand', $._expr), field('op', '.'), field('rhs', $.field))
    ),

    expr_postfix_index: $ => prec.left(
      90,
      seq(field('operand', $._expr), '[', field('body', $._expr), ']')
    ),

    expr_postfix_block: $ => prec.left(
      90,
      seq(field('operand', $._expr), '{', field('body', $._expr), '}')
    ),

    expr_postfix_call: $ => prec.left(
      90,
      seq(field('operand', $._expr), '(', optional(sepBy1(',', field('args', $._expr))), ')')
    ),

    int: $ => /[0-9]+/,

    name: $ => /[a-z]+/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
