// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'rassoc',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  rules: {
    file: $ => field('expr', $._expr),

    expr: $ => field('atom', $.int),

    _expr: $ => choice($.expr, $.expr_bin, $.expr_prefix),

    expr_bin: $ => choice(
      prec.left(10, seq(field('lhs', $._expr), field('op', '+'), field('rhs', $._expr))),
      prec.right(30, seq(field('lhs', $._expr), field('op', '^'), field('rhs', $._expr)))
    ),

    expr_prefix: $ => prec.right(50, seq(field('op', '-'), field('operand', $._expr))),

    int: $ => /[0-9]+/
  }
});
