; Generated by lingo from the grammar. Do not edit by hand.
;
; The first pattern that matches a node wins, so what is written for one
; position comes before what is written for the token itself.

; every occurrence of a token
"+" @operator
"^" @operator
"-" @operator

