; Generated by lingo from the grammar. Do not edit by hand.
;
; The last pattern that matches a node wins, so what is written for the
; token itself comes before what is written for one position.

; every occurrence of a token
"let" @keyword
"sig" @keyword
"in" @keyword
"end" @keyword
"(" @punctuation.delimiter
")" @punctuation.delimiter
"," @punctuation.delimiter
";" @punctuation.delimiter
":" @punctuation.delimiter

