// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'recovery',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  word: $ => $.name,

  rules: {
    file: $ => repeat(field('items', $.item)),

    item: $ => field('item', choice($.triple, $.group, $.sig)),

    triple: $ => seq(
      field('kw', 'let'),
      field('head', $.leaf),
      field('sep', 'in'),
      field('tail', 'end')
    ),

    group: $ => seq(field('open', '('), field('inner', $.triple), field('close', ')')),

    sig: $ => seq(field('kw', 'sig'), field('fields', $.fields), field('tail', 'in')),

    fields: $ => sepBy1(',', field('items', $.field)),

    field: $ => seq(field('lead', ':'), field('value', $.leaf), field('tail', ';')),

    leaf: $ => field('n', $.name),

    name: $ => /[a-z]+/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
