// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'rust',

  extras: $ => [
    /[\t\n\r ]+/,
    $.line
  ],

  word: $ => $.ident,

  rules: {
    file: $ => repeat(field('item', $.item)),

    item: $ => field('kind', choice($.struct, $.enum, $.trait, $.fn)),

    struct: $ => seq(
      field('kw', 'struct'),
      field('name', $.ident),
      field('body', $.struct_body)
    ),

    struct_body: $ => seq(
      '{',
      optional(seq(sepBy1(',', field('field', $.field)), optional(','))),
      '}'
    ),

    field: $ => seq(field('name', $.ident), field('colon', ':'), field('ty', $.type)),

    enum: $ => seq(field('kw', 'enum'), field('name', $.ident), field('body', $.enum_body)),

    enum_body: $ => seq(
      '{',
      optional(seq(sepBy1(',', field('variant', $.variant)), optional(','))),
      '}'
    ),

    variant: $ => seq(field('name', $.ident), optional(field('payload', $.variant_payload))),

    variant_payload: $ => field('shape', choice($.tuple_payload, $.struct_payload)),

    tuple_payload: $ => seq('(', optional(sepBy1(',', field('ty', $.type))), ')'),

    struct_payload: $ => seq(
      '{',
      optional(seq(sepBy1(',', field('field', $.field)), optional(','))),
      '}'
    ),

    trait: $ => seq(field('kw', 'trait'), field('name', $.ident), field('body', $.trait_body)),

    trait_body: $ => seq('{', repeat(field('method_', $.method_sig)), '}'),

    method_sig: $ => seq(
      field('kw', 'fn'),
      field('name', $.ident),
      field('params', $.param_list),
      field('arrow', '->'),
      field('ret_ty', $.type),
      field('semi', ';')
    ),

    fn: $ => seq(
      field('kw', 'fn'),
      field('name', $.ident),
      field('params', $.param_list),
      field('arrow', '->'),
      field('ret_ty', $.type),
      field('body', $.block)
    ),

    param_list: $ => seq(
      '(',
      optional(seq(sepBy1(',', field('param', $.param)), optional(','))),
      ')'
    ),

    param: $ => seq(field('name', $.ident), field('colon', ':'), field('ty', $.type)),

    type: $ => field('name', $.ident),

    block: $ => seq('{', repeat(field('stmt', $.stmt)), '}'),

    stmt: $ => field('kind', choice($.let, $.expr_stmt)),

    let: $ => seq(
      field('kw', 'let'),
      field('name', $.ident),
      field('eq', '='),
      field('value', $._expr),
      field('semi', ';')
    ),

    expr_stmt: $ => seq(field('expr', $._expr), field('semi', ';')),

    match: $ => seq(
      field('kw', 'match'),
      field('scrutinee', $._expr),
      field('body', $.match_body)
    ),

    match_body: $ => seq(
      '{',
      optional(seq(sepBy1(',', field('arm', $.match_arm)), optional(','))),
      '}'
    ),

    match_arm: $ => seq(
      field('pat', choice($.ident, $.int)),
      field('fat_arrow', '=>'),
      field('body', $._expr)
    ),

    expr: $ => field('atom', choice($.int, $.ident)),

    _expr: $ => choice(
      $.expr,
      $.expr_bin,
      $.expr_prefix,
      $.expr_postfix_try,
      $.expr_postfix_field,
      $.expr_postfix_index,
      $.expr_postfix_call,
      $.block,
      $.match
    ),

    expr_bin: $ => choice(
      prec.right(1, seq(field('lhs', $._expr), field('op', '='), field('rhs', $._expr))),
      prec.left(5, seq(field('lhs', $._expr), field('op', '=='), field('rhs', $._expr))),
      prec.left(5, seq(field('lhs', $._expr), field('op', '!='), field('rhs', $._expr))),
      prec.left(10, seq(field('lhs', $._expr), field('op', '+'), field('rhs', $._expr))),
      prec.left(10, seq(field('lhs', $._expr), field('op', '-'), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '*'), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '/'), field('rhs', $._expr)))
    ),

    expr_prefix: $ => prec.right(60, seq(field('op', '!'), field('operand', $._expr))),

    expr_postfix_try: $ => prec.left(100, seq(field('operand', $._expr), field('op', '?'))),

    expr_postfix_field: $ => prec.left(
      100,
      seq(field('operand', $._expr), field('op', '.'), field('rhs', $.ident))
    ),

    expr_postfix_index: $ => prec.left(
      100,
      seq(field('operand', $._expr), '[', field('body', $._expr), ']')
    ),

    expr_postfix_call: $ => prec.left(
      100,
      seq(
        field('operand', $._expr),
        '(',
        optional(seq(sepBy1(',', field('args', $._expr)), optional(','))),
        ')'
      )
    ),

    ident: $ => /[A-Z_a-z][0-9A-Z_a-z]*/,

    int: $ => /[0-9]+/,

    line: $ => /\/\/[^\n]*/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
