; Generated by lingo from the grammar. Do not edit by hand.
;
; A scope holds the names introduced inside it. tree-sitter's locals
; runtime walks the tree, keeps a stack of the scopes, and matches each
; reference to the nearest enclosing definition of the same text.

; a production that opens a scope
(trait) @local.scope
(method_sig) @local.scope
(fn) @local.scope
(block) @local.scope

; a child position that introduces a name
(struct name: (ident) @local.definition)
(enum name: (ident) @local.definition)
(trait name: (ident) @local.definition)
(method_sig name: (ident) @local.definition)
(fn name: (ident) @local.definition)
(param name: (ident) @local.definition)
(let name: (ident) @local.definition)

; every identifier. Where a definition above matches the same node,
; tree-sitter takes that more specific capture.
(ident) @local.reference

