; Generated by lingo from the grammar. Do not edit by hand.
;
; A rule framed by a matched pair is a fold region.

(struct_body) @fold
(enum_body) @fold
(tuple_payload) @fold
(struct_payload) @fold
(trait_body) @fold
(param_list) @fold
(block) @fold
(match_body) @fold
(expr_postfix_index) @fold
(expr_postfix_call) @fold
