; Generated by lingo from the grammar. Do not edit by hand.
;
; The last pattern that matches a node wins, so what is written for the
; token itself comes before what is written for one position.

; every occurrence of a token
"struct" @keyword
"enum" @keyword
"trait" @keyword
"fn" @keyword
"let" @keyword
"match" @keyword
"{" @punctuation.bracket
"}" @punctuation.bracket
"(" @punctuation.bracket
")" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
"," @punctuation.delimiter
";" @punctuation.delimiter
":" @punctuation.delimiter
"." @punctuation.delimiter
"?" @operator
"->" @punctuation.delimiter
"=>" @punctuation.delimiter
"=" @operator
"+" @operator
"-" @operator
"*" @operator
"/" @operator
"==" @operator
"!=" @operator
"!" @operator
(ident) @variable
(int) @number
(line) @comment

; one position of one rule
(struct name: (ident) @type)
(field name: (ident) @variable.member)
(enum name: (ident) @type)
(trait name: (ident) @type)
(method_sig name: (ident) @function)
(fn name: (ident) @function)
(param name: (ident) @variable.parameter)
(type name: (ident) @type)
(let name: (ident) @variable)

