// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'sexp',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  rules: {
    file: $ => field('root', $.sexp),

    sexp: $ => field('kind', choice($.ident, $.number, $.group)),

    group: $ => seq('(', repeat(field('elt', $.sexp)), ')'),

    ident: $ => /[!*+\-\/<-?A-Z_a-z][!*+\-\/-9<-?A-Z_a-z]*/,

    number: $ => /-?[0-9]+(?:\.[0-9]+)?/
  }
});
