; Generated by lingo from the grammar. Do not edit by hand.
;
; A scope holds the names introduced inside it. tree-sitter's locals
; runtime walks the tree, keeps a stack of the scopes, and matches each
; reference to the nearest enclosing definition of the same text.

; every identifier. Where a definition above matches the same node,
; tree-sitter takes that more specific capture.
(name) @local.reference

