// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'shapes',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  word: $ => $.name,

  rules: {
    program: $ => repeat(field('decls', $.decl)),

    decl: $ => field('decl', choice($.let, $.block)),

    let: $ => seq(
      field('kw', 'let'),
      field('name', $.name),
      optional(field('marker', '@')),
      optional(field('init', $.init))
    ),

    init: $ => seq(field('eq', '='), field('value', $.names)),

    names: $ => sepBy1(',', field('items', $.name)),

    block: $ => seq('{', optional(seq(sepBy1(';', field('items', $.decl)), optional(';'))), '}'),

    name: $ => /[a-z]+/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
