// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'unicode',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  rules: {
    file: $ => field('doc', $.doc),

    doc: $ => seq('«', optional(sepBy1('→', field('words', $.word))), '»'),

    word: $ => /[a-zÀ-ÿΑ-ω]+/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
