// Generated by lingo from the grammar. Do not edit by hand.

module.exports = grammar({
  name: 'wide',

  extras: $ => [
    /[\t\n\r ]+/
  ],

  word: $ => $.ident,

  rules: {
    file: $ => repeat1(field('stmt', $.select)),

    select: $ => seq(
      field('kw', 'select'),
      optional(field('distinct', 'distinct')),
      field('cols', $.column_list),
      field('from', $.from),
      repeat(field('joins', $.join)),
      optional(field('where', $.where)),
      optional(field('group', $.group_by)),
      optional(field('having', $.having)),
      optional(field('order', $.order_by)),
      optional(field('limit', $.limit)),
      field('semi', ';')
    ),

    column_list: $ => sepBy1(',', field('col', $.column)),

    column: $ => seq(field('value', $._expr), optional(field('alias', $.alias))),

    alias: $ => seq(field('kw', 'as'), field('name', $.ident)),

    from: $ => seq(field('kw', 'from'), field('table', $.table)),

    table: $ => seq(field('name', $.ident), optional(field('alias', $.alias))),

    join: $ => seq(
      field('kw', 'join'),
      field('table', $.table),
      field('on', 'on'),
      field('cond', $._expr)
    ),

    where: $ => seq(field('kw', 'where'), field('cond', $._expr)),

    group_by: $ => seq(field('kw', 'group'), field('by', 'by'), field('keys', $.key_list)),

    key_list: $ => sepBy1(',', field('key', $._expr)),

    having: $ => seq(field('kw', 'having'), field('cond', $._expr)),

    order_by: $ => seq(field('kw', 'order'), field('by', 'by'), field('keys', $.order_list)),

    order_list: $ => sepBy1(',', field('key', $.order_key)),

    order_key: $ => seq(field('value', $._expr), optional(field('dir', $.direction))),

    direction: $ => field('how', choice('asc', 'desc')),

    limit: $ => seq(
      field('kw', 'limit'),
      field('count', $.number),
      optional(field('offset', $.offset))
    ),

    offset: $ => seq(field('kw', 'offset'), field('count', $.number)),

    paren: $ => seq('(', field('inner', $._expr), ')'),

    expr: $ => field('atom', choice($.ident, $.number, $.string)),

    _expr: $ => choice($.expr, $.expr_bin, $.expr_postfix_field, $.paren),

    expr_bin: $ => choice(
      prec.left(5, seq(field('lhs', $._expr), field('op', 'or'), field('rhs', $._expr))),
      prec.left(10, seq(field('lhs', $._expr), field('op', 'and'), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '='), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '<'), field('rhs', $._expr))),
      prec.left(20, seq(field('lhs', $._expr), field('op', '>'), field('rhs', $._expr)))
    ),

    expr_postfix_field: $ => prec.left(
      90,
      seq(field('operand', $._expr), field('op', '.'), field('rhs', $.ident))
    ),

    ident: $ => /[A-Z_a-z][0-9A-Z_a-z]*/,

    number: $ => /[0-9]+/,

    string: $ => /"[^"\\]*"/
  }
});

function sepBy1(sep, rule) {
  return seq(rule, repeat(seq(sep, rule)));
}
