; Generated by lingo from the grammar. Do not edit by hand.
;
; The first pattern that matches a node wins, so what is written for one
; position comes before what is written for the token itself.

; one position of one rule
(alias name: (ident) @variable.member)
(table name: (ident) @type)

; every occurrence of a token
"select" @keyword
"distinct" @keyword
"from" @keyword
"as" @keyword
"join" @keyword
"on" @keyword
"where" @keyword
"group" @keyword
"by" @keyword
"having" @keyword
"order" @keyword
"asc" @keyword
"desc" @keyword
"limit" @keyword
"offset" @keyword
"and" @operator
"or" @operator
"," @punctuation.delimiter
";" @punctuation.delimiter
"." @punctuation.delimiter
"(" @punctuation.bracket
")" @punctuation.bracket
"=" @operator
"<" @operator
">" @operator
(ident) @variable
(number) @number
(string) @string

