(* -- every rejection is deserved ----------------------------------------------

      (a) For every code in [Error.codes] there is a witness grammar that
          provokes that code and no other.
      (b) [Error.codes] lists every code the checker emits: no witness
          produces one outside it.
      (c) Every check runs at the stage its code is filed under in
          [Error.codes_by_stage].
      (d) Every grammar in the accepted corpus yields a [Facts.t].
      (e) Findings come back sorted and free of duplicates.
      (f) One left-recursive cycle is one finding, whatever its length, and
          it shows the cycle in order.
      (g) A left recursion shows the shortest way round and the rewrite its
          shape suggests, and an operator conflict names its block and the
          operators that follow.

      Mechanism: an oracle over the witness corpus, with no baseline. Part (c)
      is a cross-check between the stage a code is filed under and the stage
      that emits it.

      Why each part is separate from the others. Part (a) compares sets of
      codes, so a check that reports one code k times collapses to the same set
      and (a) stays green; part (f) carries the count for that reason. Part (c)
      cross-checks the stage a code is filed under against the stage that emits
      it, so a check moved from one stage to another passes (a) and fails (c).
      Part (e) rejects findings that are identical, which a left recursion
      reported per member is not: the members differ in their site and message.
      Each part exists because the one beside it cannot see something.

      Part (g) reads the details the author sees. Parts (a) to (f) compare
      codes, so a report that showed the wrong path or suggested the wrong
      rewrite would pass all of them. Each detail is rendered as one line and
      compared with what the grammar's shape says it should be. One grammar
      has a longer way round beside the shortest, so a search that took the
      first path it found would show the wrong one.

      Why the left recursions report one code. Every left recursion also
      makes the child that carries it overlap what the rule takes first. The
      checker leaves that conflict out, so each of part (f)'s six cycles
      reports the recursion alone. Drop that and a cycle of n rules reports
      n conflicts beside it.

      Where a collision is recorded. The duplicate-child-name witness lives
      here rather than under test/laws/law_manifest.ml, because that law reads
      the manifest for the collision and finds it either way. This one reads
      whether the checker refused the grammar.

      The one test with a blast radius. Dropping the self-edge test on a
      one-rule component makes every rule a component of its own, so every
      grammar in the tree is rejected: 21 findings here, 15 in law_facts, 10
      each in law_first_follow and law_manifest, and one apiece from sexp_facts
      and pratt_desugar, because each needs a [Facts.t] the checker now refuses
      to build. That one test is what separates a rule from a rule that reaches
      itself.

      Why (c) is separate from (a). A check that moves stage keeps its witness
      rejected, so (a) still passes: the grammar is refused, just not where the
      code says it is refused. (c) is the part that reads the stage.

      Coverage. The 63 witness grammars and the 11 accepted ones: at least
      one grammar per rejection and a handful of near misses, together with
      the six cycles part (f) builds for itself. It says nothing about whether
      a check's reason is right, only that it fires on one shape and stays
      quiet on eleven others. Eleven accepted grammars is a statement about eleven
      grammars; a generated corpus is what would make it a statement about
      the checker.
   -------------------------------------------------------------------------- *)

(* The four blocks below are generated, and they are the evidence. assay
   derives a mutation from the code rather than from a sentence beside it,
   applies every one, and records what went red. Regenerate them with

     assay -config assay.conf -only core

   and take the counts as they come: they move whenever the corpus grows, and
   asserting them exactly would train everyone to ignore a red suite. What they
   assert is that every mutant dies. A survivor is the finding, and the lines it
   names are where to look. *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/core/check_names.ml, 57 mutants, 55 killed, 2 survived.
        extreme     14  all killed, law_validate invalid-name:: 8, law_lower rust:: 2, law_validate empty-grammar:: 2, law_validate postfix-suffix-missing:: 1, law_validate unknown-delimiter-token:: 1
        sbr         10  all killed, dup-kind-name: 1 dup-pratt-op: 1 dup-root: 1 invalid-token-literal: 1 mixed-assoc-at-bp: 1 no-roots: 1 nullable-token: 1 postfix-suffix-duplicate: 1 unknown-op-token: 1 unknown-rule: 1
        ror         12  all killed, law_lower calc:: 3, law_lower sexp:: 3, law_validate dup-kind-name:: 2, law_validate postfix-suffix-missing:: 2, law_lower postfix:: 1, law_validate invalid-name:: 1
        lcr          2  1 killed, calc: 1; 1 survived
        aor          1  0 killed; 1 survived
        uoi         18  all killed, law_lower calc:: 6, law_lower sexp:: 6, law_lower postfix:: 2, law_validate dup-kind-name:: 2, law_validate invalid-name:: 1, law_validate postfix-suffix-missing:: 1
      survived in collisions (lcr), pratt (aor)
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/core/check_shape.ml, 23 mutants, 21 killed, 2 survived.
        extreme      6  4 killed, unused-resync-anchors: 3 delimited-arity: 1; 2 survived
        sbr          4  all killed, repeated-vs-single: 2 delimited-arity: 1 unused-resync-anchors: 1
        ror          6  all killed, law_lower ml:: 2, law_lower sexp:: 2, law_lower shapes:: 1, law_validate repeated-vs-single:: 1
        lcr          1  all killed, sexp: 1
        uoi          6  all killed, law_lower sexp:: 2, law_lower comments:: 1, law_lower json:: 1, law_lower ml:: 1, law_validate repeated-vs-single:: 1
      survived in kind_refs (extreme), child_kinds (extreme)
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-07 ---------------------
      lib/core/check_full.ml, 224 mutants, 179 killed, 44 survived, 1 timed out.
        extreme     25  all killed, first-first-conflict: 13 (g) 4 left-recursion: 3 unused-message-child: 3 a 1 metavariable-clash: 1
        sbr         81  65 killed, law_validate left-recursion:: 19, law_validate a: 6, law_validate empty-first-set:: 5, law_validate first-follow-conflict:: 5, law_validate nullable-repeated:: 5, law_validate operator-follow-conflict:: 5, law_lower sexp:: 3, law_validate (g): 3, law_validate token-unreachable:: 3, law_validate: 2, law_validate metavariable-clash:: 2, law_lower: 1, law_validate ambiguous-empty:: 1, law_validate nullable-pratt-atom:: 1, law_validate pratt-atom-conflict:: 1, law_validate prefix-atom-conflict:: 1, law_validate resync-anchor-conflict:: 1, law_validate unused-message-child:: 1; 15 survived; 1 timed out
        ror         37  22 killed, law_validate (g): 3, law_validate a: 3, law_lower: 2, law_lower rust:: 2, law_validate left-recursion:: 2, law_validate nullable-repeated:: 2, law_lower calc:: 1, law_lower sexp:: 1, law_validate: 1, law_validate empty-first-set:: 1, law_validate first-first-conflict:: 1, law_validate pratt-atom-conflict:: 1, law_validate prefix-atom-conflict:: 1, law_validate token-unreachable:: 1; 15 survived
        lcr         19  12 killed, law_lower: 3, law_lower sexp:: 3, law_validate left-recursion:: 2, law_lower calc:: 1, law_validate (g): 1, law_validate a: 1, law_validate first-follow-conflict:: 1; 7 survived
        aor         13  12 killed, law_lower: 8, law_validate (g): 2, law_lower sexp:: 1, law_validate: 1; 1 survived
        uoi         45  41 killed, law_lower: 7, law_lower sexp:: 7, law_validate left-recursion:: 6, law_lower calc:: 4, law_validate a: 4, law_lower rust:: 2, law_validate: 2, law_facts required-empty:: 1, law_lower effekt:: 1, law_lower json:: 1, law_lower shapes:: 1, law_validate empty-first-set:: 1, law_validate first-first-conflict:: 1, law_validate nullable-repeated:: 1, law_validate prefix-atom-conflict:: 1, law_validate token-unreachable:: 1; 4 survived
        empty        4  2 killed, first-first-conflict: 1 pratt-atom-conflict: 1; 2 survived
      survived in left_edges (ror), cyclic_components (sbr 2, ror 2),
        cycle_path (lcr 2), left_rewrite (ror 3, lcr 2, aor),
        first_first (lcr), first_follow (sbr 2, lcr, uoi, empty),
        operator_follow (sbr 2, empty), unused_overrides (ror),
        nullable_pratt_and_separated (ror 2), empty_first_sets (sbr 6, ror),
        prefix_atom_conflict (ror),
        token_reachability (sbr 2, ror 3, lcr, uoi 3),
        metavariable_clash (sbr), run (ror)
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-07 ---------------------
      lib/core/error.ml, 66 mutants, 56 killed, 10 survived.
        extreme     12  2 killed, (g) 1 empty-grammar: 1; 10 survived
        sbr         54  all killed, ambiguous-empty 2 ambiguous-same-kind-child 2 binder-not-pattern-token 2 delimited-arity 1 dup-child-name 1 dup-kind-name 1 dup-pratt-op 1 dup-root 1 empty-first-set 1 empty-grammar 1 empty-pratt-atoms 1 first-first-conflict 1 first-follow-conflict 1 invalid-name 1 invalid-token-literal 1 left-recursion 1 metavariable-clash 1 mixed-assoc-at-bp 1 mixed-pratt-role 1 name-collision 1 no-roots 1 nullable-pratt-atom 1 nullable-repeated 1 nullable-separated-element 1 nullable-token 1 operator-follow-conflict 1 overlapping-single-kinds 1 postfix-suffix-duplicate 1 postfix-suffix-missing 1 pratt-atom-conflict 1 prefix-atom-conflict 1 repeated-vs-single 1 repeated-vs-single-kinds 1 reserved-name 1 resync-anchor-conflict 1 root-is-block 1 separated-arity 1 token-unreachable 1 unknown-binder-child 1 unknown-delimiter-token 1 unknown-identity-child 1 unknown-message-child 1 unknown-op-token 1 unknown-recover-to-token 1 unknown-resync-anchor 1 unknown-root 1 unknown-rule 1 unknown-token 1 unused-message-child 1 unused-recover-to 1 unused-resync-anchors 1
      survived in listed (extreme), kinds (extreme), plain (extreme),
        hint (extreme), message (extreme 2), pp_where (extreme),
        where_rank (extreme), compare_where (extreme), compare (extreme)
   ---------------------------------------------------------------------- *)

let codes_of = function
  | Ok _ -> []
  | Error es ->
    List.sort_uniq
      String.compare
      (List.map (fun (e : Core.Error.t) -> Core.Error.code e) es)
;;

let stage_of_code (code : string) : string option =
  List.find_map
    (fun (stage, cs) -> if List.mem code cs then Some stage else None)
    Core.Error.codes_by_stage
;;

(* (a) and (b) *)
let () =
  List.iter
    (fun (code, g) ->
       match codes_of (Core.Facts.of_grammar g) with
       | [] -> Law.fail "%s: the witness grammar was accepted" code
       | [ c ] when c = code -> Law.pass "%s: witness provokes exactly it" code
       | cs ->
         Law.fail
           "%s: witness provokes {%s} instead of exactly it"
           code
           (String.concat ", " cs))
    Lingo_witness.Witnesses.all
;;

let () =
  let witnessed =
    List.sort_uniq String.compare (List.map fst Lingo_witness.Witnesses.all)
  in
  let declared = List.sort_uniq String.compare Core.Error.codes in
  List.iter
    (fun c ->
       if not (List.mem c witnessed)
       then
         Law.fail
           "%s is in Error.codes but has no witness: it is untested or unreachable, and \
            both are findings"
           c)
    declared;
  List.iter
    (fun c ->
       if not (List.mem c declared) then Law.fail "%s is emitted but not in Error.codes" c)
    witnessed;
  if List.length Core.Error.codes <> List.length declared
  then Law.fail "Error.codes contains a duplicate";
  List.iter
    (fun c ->
       if stage_of_code c = None
       then Law.fail "%s is in Error.codes but in no stage list" c)
    declared;
  if Law.failures () = 0
  then Law.pass "Error.codes and the witness table are the same set"
;;

(* (c). The one caller of [Internal]. A code filed under "names" and caught
   at the third stage passes the completeness law while reporting two
   derivations later than it could, and running the stages one at a time is
   how that shows. *)

let () =
  List.iter
    (fun (code, g) ->
       let declared = Option.get (stage_of_code code) in
       let n = Core.Internal.Stage.names g in
       let s1 = Core.Internal.Check_names.run n in
       let observed =
         if s1 <> []
         then "names"
         else (
           let shape = Core.Internal.Stage.shape n in
           if Core.Internal.Check_shape.run shape <> []
           then "shape"
           else if
             Core.Internal.Check_full.run
               shape
               (Core.Internal.Fixpoint.compute
                  ~rules:shape.rules
                  ~blocks:shape.blocks
                  ~kind_rule:shape.names.kind_rule)
               (Core.Internal.Stage.lexer n)
             <> []
           then "full"
           else "accepted")
       in
       if observed = declared
       then Law.pass "%s: rejected at stage %s, as filed" code declared
       else Law.fail "%s: filed under stage %s but rejected at %s" code declared observed)
    Lingo_witness.Witnesses.all
;;

(* (e). Several checks build their reports by folding a hash table, so the
   sort is what fixes the order a caller sees. *)
let () =
  List.iter
    (fun (code, g) ->
       match Core.Facts.of_grammar g with
       | Ok _ -> ()
       | Error es ->
         if List.sort Core.Error.compare es <> es
         then Law.fail "%s: findings are not sorted" code
         else if List.sort_uniq Core.Error.compare es <> es
         then Law.fail "%s: findings contain a duplicate" code)
    Lingo_witness.Witnesses.all;
  if Law.failures () = 0 then Law.pass "findings are sorted and duplicate-free"
;;

(* (d) *)
let () =
  List.iter
    (fun (name, g) ->
       match Core.Facts.of_grammar g with
       | Ok _ -> Law.pass "accepted: %s" name
       | Error es ->
         Law.fail
           "accepted corpus grammar %s was rejected:@\n%a"
           name
           Core.Error.pp_list
           es)
    Lingo_witness.Witnesses.accepted
;;

(* One left recursion's members, its way round and its rewrite, as one line. *)
let left_shape (es : Core.Error.t list) : string =
  let rule = Core.Grammar.Name.Rule.to_string in
  let found =
    List.filter_map
      (fun (e : Core.Error.t) ->
         match e.detail with
         | Core.Error.Left_recursion { members; steps; rewrite } ->
           Some (members, steps, rewrite)
         | _ -> None)
      es
  in
  match found with
  | [ (members, steps, rewrite) ] ->
    let step (s : Core.Error.left_step) =
      match s.through with
      | Core.Error.Through_child c ->
        Printf.sprintf
          "%s -%s-> %s"
          (rule s.rule)
          (Core.Grammar.Name.Child.to_string c)
          (rule s.reaches)
      | Core.Error.Through_atom ->
        Printf.sprintf "%s -atom-> %s" (rule s.rule) (rule s.reaches)
    in
    let rewrite =
      match rewrite with
      | Core.Error.Repeat { rule = r; child } ->
        Printf.sprintf "repeat %s.%s" (rule r) (Core.Grammar.Name.Child.to_string child)
      | Core.Error.Operator { block; rule = r; lead; infix } ->
        Printf.sprintf
          "%s %s of %s on %s"
          (if infix then "infix" else "postfix")
          (rule r)
          (rule block)
          (Core.Grammar.Name.Token.to_string lead)
      | Core.Error.Break_cycle -> "break"
    in
    Printf.sprintf
      "%s | %s | %s"
      (String.concat "," (List.map rule members))
      (String.concat ", " (List.map step steps))
      rewrite
  | ds -> Printf.sprintf "%d left recursions" (List.length ds)
;;

(* (f). The property is about the length of the cycle and the witness table
   fixes two lengths, so these are built here and quantified over. A cycle of
   one is the length at which reporting rotations and reporting components
   agree, which is why the corpus on its own could not separate them. *)
let () =
  let name i = Printf.sprintf "P%d" i in
  let cycle n =
    Grammar.create
      ~tokens:[ Grammar.punct_tight ~name:"ta" "a" ]
      ~roots:[ name 0 ]
      (List.init n (fun i ->
         Grammar.prod
           (name i)
           [ Grammar.child_opt "l" (Grammar.Rule (name ((i + 1) mod n)))
           ; Grammar.child_req "t" (Grammar.Token "ta")
           ]))
  in
  List.iter
    (fun n ->
       match Core.Facts.of_grammar (cycle n) with
       | Ok _ -> Law.fail "a cycle of %d rules was accepted" n
       | Error es ->
         let want =
           Printf.sprintf
             "%s | %s | %s"
             (String.concat "," (List.init n name))
             (String.concat
                ", "
                (List.init n (fun i -> name i ^ " -l-> " ^ name ((i + 1) mod n))))
             (if n = 1 then "repeat P0.l" else "break")
         in
         (match left_shape es with
          | got when got = want -> ()
          | got ->
            Law.fail "a cycle of %d rules shows %s, where it should show %s" n got want);
         let mine =
           List.filter (fun (e : Core.Error.t) -> Core.Error.code e = "left-recursion") es
         in
         if List.length es <> 1 || List.length mine <> 1
         then
           Law.fail
             "a cycle of %d rules reports %d findings, %d of them left-recursion: one \
              cycle is one left recursion"
             n
             (List.length es)
             (List.length mine))
    [ 1; 2; 3; 4; 5; 8 ];
  if Law.failures () = 0
  then Law.pass "one left recursion is one finding, at every cycle length"
;;

(* (g) *)
let () =
  let before = Law.failures () in
  let open Core.Grammar in
  let tokens =
    [ punct_tight ~name:"ta" "a"
    ; punct_tight ~name:"tb" "b"
    ; punct_tight ~name:"m" "-"
    ; punct_tight ~name:"lp" "("
    ; punct_tight ~name:"rp" ")"
    ; punct_tight ~name:"comma" ","
    ]
  in
  let rejections (g : t) : Core.Error.t list =
    match Core.Facts.of_grammar g with
    | Ok _ -> []
    | Error es -> es
  in
  let left =
    [ ( "the direct witness"
      , Lingo_witness.Witnesses.left_recursion
      , "Root | Root -l-> Root | repeat Root.l" )
    ; ( "the pair witness"
      , Lingo_witness.Witnesses.left_recursion_pair
      , "Root,Inner | Root -l-> Inner, Inner -l-> Root | break" )
    ; ( "the operator witness"
      , Lingo_witness.Witnesses.left_recursion_operator
      , "Add,E | Add -l-> E, E -atom-> Add | infix Add of E on t" )
    ; ( "an atom that ends in a token"
      , create
          ~tokens
          ~roots:[ "Root" ]
          ~expr:[ expr_block ~rule_name:"E" ~atoms:[ Token "ta"; Rule "Call" ] () ]
          [ prod "Root" [ child_req "e" (Rule "E") ]
          ; prod
              "Call"
              [ child_req "f" (Rule "E")
              ; child_req "lp" (Token "lp")
              ; child_req "rp" (Token "rp")
              ]
          ]
      , "Call,E | Call -f-> E, E -atom-> Call | postfix Call of E on lp" )
    ; ( "a cycle with a longer way round beside the shortest"
      , create
          ~tokens
          ~roots:[ "A" ]
          [ prod "A" [ child_opt "b" (Rule "B"); child_req "t" (Token "ta") ]
          ; prod
              "B"
              [ child_opt "c" (Rule "C")
              ; child_opt "a" (Rule "A")
              ; child_req "t" (Token "tb")
              ]
          ; prod "C" [ child_opt "a" (Rule "A"); child_req "t" (Token "m") ]
          ]
      , "A,B,C | A -b-> B, B -a-> A | break" )
    ]
  in
  List.iter
    (fun (what, g, want) ->
       let got = left_shape (rejections g) in
       if got <> want
       then Law.fail "(g) %s shows %s, where it should show %s" what got want)
    left;
  let operator_shape (es : Core.Error.t list) : string =
    String.concat
      "; "
      (List.filter_map
         (fun (e : Core.Error.t) ->
            match e.detail with
            | Core.Error.Operator_follow_conflict { block; common } ->
              Some
                (Printf.sprintf
                   "%s on %s"
                   (Core.Grammar.Name.Rule.to_string block)
                   (String.concat
                      ","
                      (List.map
                         (fun (k : Core.Error.kind_ref) ->
                            Core.Kind.Name.to_string k.name)
                         common)))
            | _ -> None)
         es)
  in
  let operator =
    [ "the witness", Lingo_witness.Witnesses.operator_follow_conflict, "E on T_T"
    ; ( "a repeated expression, whose next element can start with an operator"
      , create
          ~tokens
          ~roots:[ "Root" ]
          ~expr:
            [ expr_block
                ~rule_name:"E"
                ~atoms:[ Token "ta" ]
                ~prefix_ops:[ prefix ~token:"m" ~bp:70 () ]
                ~infix_ops:[ infix ~token:"m" ~bp:10 () ]
                ()
            ]
          [ prod "Root" [ child_rep "e" (Rule "E") ] ]
      , "E on T_M" )
    ; ( "an expression in brackets whose closer is an operator"
      , create
          ~tokens
          ~roots:[ "Root" ]
          ~expr:
            [ expr_block
                ~rule_name:"E"
                ~atoms:[ Token "ta" ]
                ~infix_ops:[ infix ~token:"rp" ~bp:10 () ]
                ()
            ]
          [ prod "Root" [ child_req "e" (Rule "E") ]
            |> with_delimited ~open_tok:"lp" ~close_tok:"rp"
          ]
      , "E on T_RP" )
    ]
  in
  List.iter
    (fun (what, g, want) ->
       let got = operator_shape (rejections g) in
       if got <> want
       then Law.fail "(g) %s reports %S, where it should report %S" what got want)
    operator;
  if Law.failures () = before
  then
    Law.pass
      "(g) every left recursion shows its way round and its rewrite, and every operator \
       conflict names its block, over %d grammars"
      (List.length left + List.length operator)
;;

let () = Law.summarise "law_validate"
