(* -- first, follow and nullability --------------------------------------------

      FIRST, FOLLOW and nullability over kind bitsets agree, rule for rule and
      token for token, with a naive recomputation over the grammar using string
      sets.

      And the two one-sided laws the sets owe, checked against the structure:
      FOLLOW holds everything the naive walk finds, and nullability holds every
      rule the naive walk finds nullable.

      Mechanism: a cross-check. [Core.Internal.Fixpoint] walks resolved
      rules with bitsets over kind integers; [Naive_first] walks the grammar
      with [Set.Make(String)] over token names and shares no code with it.

      What a cross-check cannot see. The survivor at fixpoint.ml:335 in the
      record below is the separator of an enclosed postfix with [Many]
      content, dropped, so a call's comma leaves FOLLOW. [Naive_first] carries
      the same clause written the same way, so the omission would have to be
      made twice for either side to disagree with the other. That is a limit of
      the mechanism rather than a gap in the corpus. The corpus does not reach
      it either: one grammar has a separated postfix call, its element is the
      block itself, and no check that runs consults the FOLLOW that changed.
      The sampler law would catch it, because a FOLLOW missing a separator
      makes recovery skip a comma a generated input holds.

      Coverage. The accepted corpus, and rules whose origin is [User] or
      [Pratt_block]. The naive side does not desugar, so it has no counterpart
      for a role rule. A role rule's FIRST is covered here by nothing; what
      covers it is that the pratt grammars are accepted, which requires only that
      it is non-empty.
   -------------------------------------------------------------------------- *)

(* The block below is generated, and it is the evidence. assay derives a
   mutation from the code rather than from a sentence beside it, applies
   every one, and records what went red. Regenerate it with

     assay -config assay.conf -only core

   and take the counts as they come: they move whenever the corpus grows,
   and asserting them exactly would train everyone to ignore a red suite.
   What it asserts is that every mutant dies. A survivor is the finding,
   and the lines it names are where to look. *)

(* -- mutation testing, generated by assay on 2026-10-07 ---------------------
      lib/core/fixpoint.ml, 179 mutants, 146 killed, 16 survived, 17 timed out.
        extreme     32  all killed, law_lower sexp:: 6, law_sample (e): 6, law_first_follow ml/File: 3, law_lower: 3, law_facts: 2, law_facts json/Member.key:: 2, law_facts sexp/Sexp.kind:: 1, law_first_follow calc/Parens: 1, law_first_follow required-empty/Root: 1, law_first_follow sexp/Sexp: 1, law_lower (a): 1, law_lower shapes:: 1, law_validate (g): 1, law_validate first-first-conflict:: 1, law_validate first-follow-conflict:: 1, law_validate unused-message-child:: 1
        sbr         59  51 killed, law_facts json/Member.key:: 6, law_first_follow sexp/Sexp: 6, law_lower shapes:: 6, law_first_follow calc/Parens: 5, law_facts ml/TypeGroup.ty:: 4, law_lower sexp:: 4, law_first_follow ml/File: 3, law_facts ml/If.kw:: 2, law_first_follow ml/Arg: 2, law_lower effekt:: 2, law_sample (e): 2, dump_plan: 1, law_facts ml/ExprPostfixField.operand:: 1, law_facts pratt-postfix/EPostfixBang.operand:: 1, law_first_follow ml/Path: 1, law_first_follow ml/Stmt: 1, law_first_follow required-empty/Lead: 1, law_first_follow sexp/Group: 1, law_lower: 1, law_validate first-follow-conflict:: 1; 4 survived; 4 timed out
        ror         18  6 killed, law_facts json/Member.key:: 1, law_facts ml/TypeGroup.ty:: 1, law_first_follow calc/File: 1, law_first_follow calc/Parens: 1, law_lower: 1, law_lower shapes:: 1; 8 survived; 4 timed out
        lcr          4  3 killed, law_lower: 2, law_lower sexp:: 1; 1 timed out
        aor         17  15 killed, law_lower: 15; 1 survived; 1 timed out
        uoi         30  23 killed, law_lower: 10, law_lower effekt:: 4, law_lower sexp:: 3, law_facts json/Member.key:: 2, law_lower shapes:: 2, law_facts required-empty:: 1, law_lower recovery:: 1; 7 timed out
        empty       19  16 killed, law_facts json/Member.key:: 3, law_lower sexp:: 3, law_first_follow ml/List: 2, law_first_follow sexp/Sexp: 2, law_facts ml/Stmt.e:: 1, law_first_follow calc/File: 1, law_first_follow calc/Parens: 1, law_first_follow json/Value: 1, law_first_follow required-empty/Lead: 1, law_lower (a): 1; 3 survived
      survived in solve (sbr), body_children (aor), rule_of_kind (ror),
        context (sbr 2, ror), kind_nullable (ror), kind_first (ror),
        rule_targets (ror), min_size (ror), first (empty),
        follow (ror, empty), enclosing (ror), Reader.suffix_first (sbr, empty)
   ---------------------------------------------------------------------- *)

module String_set = Set.Make (String)

(* The fast side's sets are kinds; the naive side's are token names. Compare
   in the naive side's alphabet: a kind that is a token becomes the token's
   name, and a kind that is not is a defect in itself. FIRST and FOLLOW hold
   terminals. *)
let to_token_names (f : Core.Facts.t) (set : Core.Kind.Set.t) : String_set.t =
  Core.Kind.Set.fold
    (fun k acc ->
       match Core.Facts.token_of_kind f k with
       | Some t -> String_set.add (Grammar.Name.Token.to_string t.Core.Token.name) acc
       | None ->
         Law.fail
           "a FIRST/FOLLOW set holds %s, which is not a token kind"
           (Core.Kind.Name.to_string (Core.Facts.kind_name f k));
         acc)
    set
    String_set.empty
;;

let show s = "{" ^ String.concat ", " (String_set.elements s) ^ "}"

let check_grammar ((name : string), (g : Core.Grammar.t)) : unit =
  match Core.Facts.of_grammar g with
  | Error _ -> Law.fail "%s: the corpus grammar was rejected" name
  | Ok f ->
    let naive = Naive_first.compute g in
    let get tbl r = Option.value ~default:String_set.empty (Hashtbl.find_opt tbl r) in
    Array.iter
      (fun (d : Core.Rule.def) ->
         match d.origin with
         | Core.Rule.Pratt_role _ -> ()
         | Core.Rule.User | Core.Rule.Pratt_block ->
           let fast_first = to_token_names f (Core.Facts.first_of f d.id)
           and fast_follow = to_token_names f (Core.Facts.follow_of f d.id)
           and fast_null = Core.Facts.is_nullable f d.id in
           let slow_first = get naive.first (Grammar.Name.Rule.to_string d.name)
           and slow_follow = get naive.follow (Grammar.Name.Rule.to_string d.name)
           and slow_null =
             Option.value
               ~default:false
               (Hashtbl.find_opt naive.nullable (Grammar.Name.Rule.to_string d.name))
           in
           if not (String_set.equal fast_first slow_first)
           then
             Law.fail
               "%s/%s FIRST: bitset %s vs naive %s"
               name
               (Grammar.Name.Rule.to_string d.name)
               (show fast_first)
               (show slow_first);
           if not (String_set.equal fast_follow slow_follow)
           then
             Law.fail
               "%s/%s FOLLOW: bitset %s vs naive %s"
               name
               (Grammar.Name.Rule.to_string d.name)
               (show fast_follow)
               (show slow_follow);
           if fast_null <> slow_null
           then
             Law.fail
               "%s/%s nullable: bitset %b vs naive %b"
               name
               (Grammar.Name.Rule.to_string d.name)
               fast_null
               slow_null;
           (* B3 / B4, stated as one-sided containments so the direction is
              on the record even where equality happens to hold. *)
           if not (String_set.subset slow_follow fast_follow)
           then
             Law.fail
               "%s/%s FOLLOW is too small"
               name
               (Grammar.Name.Rule.to_string d.name);
           if slow_null && not fast_null
           then
             Law.fail
               "%s/%s nullability is under-declared"
               name
               (Grammar.Name.Rule.to_string d.name))
      f.rules;
    Law.pass "%s: %d rules agree" name (Array.length f.rules)
;;

let () = List.iter check_grammar Corpus.all
let () = Law.summarise "law_first_follow"
