(* -- the OCaml syntax builder -------------------------------------------------

      (a) A structure [Emit] builds renders to source that parses back to the
          same structure.
      (b) The same for a signature.
      (c) Rendering is stable: the source that comes back renders to itself.

      Mechanism. One structure and one signature, in test/emit_fixture, which
      reach every value [emit.mli] exports. Part (a) renders, parses the
      source with ppxlib, and compares the two trees with locations set
      aside. A built tree carries [Location.none] everywhere and a parsed one
      carries real positions, and nothing here has an opinion about positions.

      What a round trip cannot see, and why the fixture is shared. A builder
      that builds a different well-formed thing round-trips just as well: fold
      [eseq] the other way and [(b; c); a] renders, parses and compares equal
      to itself. test/expect/emit.expected holds the source instead, and the
      two read the same fixture so neither drifts from what the other checks.

      Part (a)'s oracle is not a second printer. It is ppxlib's parser, which
      carries nothing of how the tree was built, so the two agree only where
      the source says what the tree said.

      Part (c) is the weaker claim that catches what part (a) cannot: a
      printer that renders two structures the same way still round-trips each
      of them.

      Coverage. Every value in [emit.mli] appears below. There is no mechanism
      that says so, and the two files move together by hand.

      What this says nothing about. Whether the emitted code compiles, or
      means anything. It parses, which is all a syntax builder owes. The
      emitters above it owe the rest.

      What this law cannot see. Every mutation of the emitter that produces
      different but well-formed OCaml passes it: [(b; c); a] round-trips as
      happily as [a; b; c], [1 :: ()] is as well formed as [1 :: \[\]], and a
      header comment is not in the tree either way. The law reads the tree a
      parse builds, and all three of those parse.

      That is what put the emitted source in test/expect/emit.expected beside
      it. The golden is the only reader of what the emitter actually wrote.

   -------------------------------------------------------------------------- *)

(* The two blocks below are generated, and they are the evidence: one for the
   builder this law reads and one for the mangling it leans on. assay derives a
   mutation from the code rather than from a sentence beside it, applies every
   one, and records what went red. Regenerate them with

     assay -config assay.conf -only ocaml,core

   and take the counts as they come: they move whenever the corpus grows,
   and asserting them exactly would train everyone to ignore a red suite.
   What it asserts is that every mutant dies. A survivor is the finding,
   and the lines it names are where to look.

   Two of the builder's points time out rather than reddening. Both are in
   [elist], where a list cell takes two arguments, and dropping either one
   leaves law_emit running past 120 s rather than printing. The timeout is the
   kill, and it is the only thing that stops them. *)

(* -- mutation testing, generated by assay on 2026-10-03 ---------------------
      lib/ocaml/emit.ml, 44 mutants, 42 killed, 2 timed out.
        extreme      6  all killed, law_emit (a): 4, law_emit (b): 1, law_views sexp_views.ml:: 1
        sbr         33  31 killed, law_emit: 7, law_lex sexp_lexer.ml:: 6, dump_emit: 5, law_emit (a): 4, law_lex json_match.ml:: 4, law_lex unicode_match.ml:: 2, law_ahead sexp_residual.ml:: 1, law_views: 1, law_views sexp_views.ml:: 1; 2 timed out
        ror          1  all killed, sexp_residual.ml: 1
        uoi          4  all killed, law_ahead sexp_residual.ml:: 3, law_lex sexp_lexer.ml:: 1
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/core/mangle.ml, 115 mutants, 112 killed, 3 survived.
        extreme      4  all killed, law_lower sexp:: 2, law_textmate sexp:: 1, law_validate invalid-name:: 1
        sbr         61  all killed, mangle_test snake_case_acronym: 2, law_lower sexp:: 1, law_manifest dup-child-name:: 1, law_manifest name-collision:: 1, law_textmate sexp:: 1, mangle_test "and": 1, mangle_test "as": 1, mangle_test "asr": 1, mangle_test "assert": 1, mangle_test "begin": 1, mangle_test "class": 1, mangle_test "constraint": 1, mangle_test "do": 1, mangle_test "done": 1, mangle_test "downto": 1, mangle_test "else": 1, mangle_test "exception": 1, mangle_test "external": 1, mangle_test "false": 1, mangle_test "for": 1, mangle_test "fun": 1, mangle_test "function": 1, mangle_test "functor": 1, mangle_test "if": 1, mangle_test "in": 1, mangle_test "include": 1, mangle_test "inherit": 1, mangle_test "initializer": 1, mangle_test "land": 1, mangle_test "lazy": 1, mangle_test "let": 1, mangle_test "lor": 1, mangle_test "lsl": 1, mangle_test "lsr": 1, mangle_test "lxor": 1, mangle_test "method": 1, mangle_test "mod": 1, mangle_test "module": 1, mangle_test "mutable": 1, mangle_test "new": 1, mangle_test "nonrec": 1, mangle_test "object": 1, mangle_test "of": 1, mangle_test "open": 1, mangle_test "or": 1, mangle_test "private": 1, mangle_test "rec": 1, mangle_test "sig": 1, mangle_test "struct": 1, mangle_test "then": 1, mangle_test "to": 1, mangle_test "true": 1, mangle_test "try": 1, mangle_test "val": 1, mangle_test "virtual": 1, mangle_test "when": 1, mangle_test "while": 1, mangle_test "with": 1, mangle_test escape_reserved: 1, mangle_test safe_snake: 1
        ror         21  19 killed, mangle_test snake_case_acronym: 4, law_manifest sexp:: 3, law_lower sexp:: 2, law_lower: 1, law_lower json:: 1, law_lower rust:: 1, law_manifest dup-child-name:: 1, law_manifest name-collision:: 1, law_textmate: 1, law_validate a: 1, law_validate invalid-name:: 1, mangle_test: 1, mangle_test is_ident: 1; 2 survived
        lcr         15  14 killed, law_lower sexp:: 3, law_validate invalid-name:: 3, mangle_test snake_case_acronym: 3, law_manifest sexp:: 2, dump_treesitter: 1, law_textmate: 1, law_validate token-unreachable:: 1; 1 survived
        aor          5  all killed, law_lower: 2, mangle_test: 2, mangle_test snake_case_acronym: 1
        uoi          9  all killed, law_lower sexp:: 3, law_manifest sexp:: 2, law_lower: 1, law_manifest reserved-name:: 1, law_textmate: 1, mangle_test snake_case_acronym: 1
      survived in snake_case_acronym (lcr), ident_error (ror 2)
   ---------------------------------------------------------------------- *)

(* A built tree carries no positions and a parsed one carries real ones, so
   the comparison sets both kinds aside.

   The stack is the one that is easy to miss. A parser records there where it
   took a pair of parentheses off, so [(1, 2)] and a tuple built here differ
   in a field neither the source nor [location] shows. Four of this law's
   constructs are parenthesised, and all four read as different until the
   stack goes too. *)
let strip =
  object
    inherit Ppxlib.Ast_traverse.map
    method! location _ = Ppxlib.Location.none
    method! location_stack _ = []
  end
;;

(* -- the runs -------------------------------------------------------------- *)

let () =
  let src = Ocaml.Emit.render Fixture.structure in
  match Ppxlib.Parse.implementation (Lexing.from_string src) with
  | exception e -> Law.fail "(a) the source did not parse: %s" (Printexc.to_string e)
  | back ->
    if strip#structure back <> strip#structure Fixture.structure
    then Law.fail "(a) the structure that came back is not the one rendered"
    else if not (String.equal (Ocaml.Emit.render back) src)
    then Law.fail "(c) the structure rendered a second time gave different bytes"
    else
      Law.pass
        "a structure renders, parses back and renders the same, over %d bytes"
        (String.length src)
;;

let () =
  let src = Ocaml.Emit.render_signature Fixture.signature in
  match Ppxlib.Parse.interface (Lexing.from_string src) with
  | exception e -> Law.fail "(b) the source did not parse: %s" (Printexc.to_string e)
  | back ->
    if strip#signature back <> strip#signature Fixture.signature
    then Law.fail "(b) the signature that came back is not the one rendered"
    else if not (String.equal (Ocaml.Emit.render_signature back) src)
    then Law.fail "(c) the signature rendered a second time gave different bytes"
    else
      Law.pass
        "a signature renders, parses back and renders the same, over %d bytes"
        (String.length src)
;;

(* [longident] is the one value the structure above does not reach, because
   every builder that takes a path goes through it. *)
let () =
  match Ocaml.Emit.longident "A.B.c" with
  | Ppxlib.Longident.Ldot (Ppxlib.Longident.Ldot (Ppxlib.Longident.Lident "A", "B"), "c")
    -> Law.pass "a dotted path reads left to right"
  | _ -> Law.fail "longident did not read \"A.B.c\" as A then B then c"
;;

let () = Law.summarise "law_emit"
