(* -- the lowering -------------------------------------------------------------

      (a) [Check.run] accepts every plan [of_facts] builds.
      (b) Every message id in a plan indexes the catalogue beside it.
      (c) Every catalogue entry is named by at least one id in the plan.
      (d) Every constructor of [Ir.Plan.instr], and every form beside it, is
          one the corpus lowers to.
      (e) A negative kind is reported wherever a plan can hold one.
      (f) An index out of range is reported wherever a plan can hold one, an
          index in range never is, and an empty dispatch set is reported
          wherever a plan can hold one.

      Mechanism. Part (a) makes every invariant [Check] holds a post-condition
      of the lowering, rather than a fact about the plans that happen to be in
      test/expect. There are fourteen of them and this law restates none.

      Parts (b) and (c) are one walk over the plan, collecting the ids it
      names, against the catalogue's length. The walk is this law's own: the
      lowering interns an id where it needs one, and this counts them off the
      plan afterwards.

      Part (c) is the one that bites. [Messages.Builder.intern] dedupes on the
      text, so an id no instruction uses disappears wherever its
      wording matches a live entry. It only shows up on wording that is
      unique, which is rare enough to survive a reading of the catalogue and
      not a law.

      Part (d) is the claim that a plan constructor nobody can build is one
      nobody should have written. test/laws/law_plan.ml counts forms too, and
      it counts them over a plan built by hand, so a constructor reaches its
      tally because someone typed it. This one counts over the grammars, so a
      form reads zero until a grammar exists that needs it.

      Coverage. All thirteen grammars in lingo_grammars, and the six accepted
      witnesses built in test/laws/witnesses.ml. required-empty is the one that
      matters to part (a): it has required children that can match nothing,
      and a lowering that put a commit over one would fail here. A count
      prints beside the result, part (c) fails on the first entry nothing
      names, and part (d) names every form that reads zero.

      What this says nothing about. Whether the plan describes the grammar.
      That needs something that runs one, and test/laws/law_interp.ml is where
      that starts.

      Why shapes carries a wording of its own. [intern] dedupes on the text, so
      a message interned for a child that never reports disappears into a live
      entry wherever its wording matches one. shapes gives its optional child a
      wording nothing else uses for that reason and for no other; wide came with
      a second by accident. Without them the leak is invisible.

      What part (d) is and is not. It reads zero or not zero, so a lowering that
      emits a form less often still passes: the claim is about the plan's surface
      rather than about how much of it the corpus uses. It exists because
      [Ir.Plan.Cannot_exit] sat in the plan for a while with no grammar able to
      build one and no parse able to act on one, and test/laws/law_plan.ml
      counted it as reached because its fixture is written by hand.

   -------------------------------------------------------------------------- *)

(* The block below is generated, and it is the evidence. assay derives a
   mutation from the code rather than from a sentence beside it, applies every
   one, and records what went red. Regenerate it with

     assay -config assay.conf -only plan

   and take the counts as they come: they move whenever the corpus grows, and
   asserting them exactly would train everyone to ignore a red suite. What it
   asserts is that every mutant dies. A survivor is the finding, and the lines it
   names are where to look. *)

(* -- mutation testing, generated by assay on 2026-10-07 ---------------------
      lib/plan/lower.ml, 57 mutants, 51 killed, 6 survived.
        extreme     15  all killed, law_lower (a): 6, dump_parse: 4, dump_plan: 1, law_ahead (a): 1, law_interp (c): 1, law_lower: 1, law_lower (d): 1
        sbr         13  all killed, law_lower (a): 5, dump_parse: 3, dump_plan: 1, law_interp (b): 1, law_interp (c): 1, law_lower (c): 1, law_lower (d): 1
        ror          9  5 killed, law_ahead (a): 4, law_lower (d): 1; 4 survived
        lcr          4  3 killed, law_ahead (a): 1, law_interp (c): 1, law_lower: 1; 1 survived
        aor          3  all killed, law_ahead (a): 2, law_lower: 1
        uoi         11  all killed, law_lower (a): 6, law_lower (d): 2, dump_parse: 1, law_ahead (b): 1, law_interp (a): 1
        empty        2  1 killed, dump_parse: 1; 1 survived
      survived in cascade (empty), matches_nothing (ror), body_of_alt (ror),
        required (ror), repeat_ends_on_of (lcr), block_of (ror)
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/core/rule.ml, 3 mutants, 3 killed.
        extreme      1  all killed, (c) 1
        aor          2  all killed, law_lower: 2
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/grammar/grammar.ml, 10 mutants, 5 killed, 5 survived.
        sbr          2  0 killed; 2 survived
        ror          3  1 killed, law_lower: 1; 2 survived
        lcr          1  0 killed; 1 survived
        uoi          2  all killed, law_lower: 2
        empty        2  all killed, unknown-binder-child: 1 unknown-message-child: 1
      survived in always (sbr), lookahead_n (sbr, ror 2, lcr)
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/grammar/name.ml, 4 mutants, 3 killed, 1 survived.
        extreme      4  3 killed, dump_parse: 1, law_lower json:: 1, law_lower sexp:: 1; 1 survived
      survived in Make.pp (extreme)
   ---------------------------------------------------------------------- *)

let grammars =
  [ "sexp", Lingo_grammars.Sexp_grammar.grammar
  ; "json", Lingo_grammars.Json_grammar.grammar
  ; "calc", Lingo_grammars.Calc_grammar.grammar
  ; "rassoc", Lingo_grammars.Rassoc_grammar.grammar
  ; "postfix", Lingo_grammars.Postfix_grammar.grammar
  ; "shapes", Lingo_grammars.Shapes_grammar.grammar
  ; "unicode", Lingo_grammars.Unicode_grammar.grammar
  ; "recovery", Lingo_grammars.Recovery_grammar.grammar
  ; "comments", Lingo_grammars.Comments_grammar.grammar
  ; "rust", Lingo_grammars.Rust_grammar.grammar
  ; "effekt", Lingo_grammars.Effekt_grammar.grammar
  ; "wide", Lingo_grammars.Wide_grammar.grammar
  ; "ml", Lingo_grammars.Ml_grammar.grammar
  ]
;;

(* The accepted witnesses carry five of the grammars above, so those are left
   out here. *)
let corpus =
  grammars
  @ List.filter
      (fun (name, _) -> not (List.mem_assoc name grammars))
      Lingo_witness.Witnesses.accepted
;;

(* Every message id the plan names, wherever it names one. *)
let ids_in (p : Ir.Plan.t) =
  let seen = Hashtbl.create 32 in
  let note id = Hashtbl.replace seen (Ir.Message.to_int id) () in
  let rec instr (i : Ir.Plan.instr) =
    match i with
    | Open _ | Close | Trivia | Bump | Call _ | Pratt _ -> ()
    | Bump_reporting id -> note id
    | Drain id -> note id
    | Expect e -> note e.message
    | Seq xs -> Array.iter instr xs
    | Alt a ->
      Array.iter (fun (_, body) -> instr body) a.arms;
      instr a.otherwise
    | Commit c ->
      note c.message;
      instr c.body
    | Loop l ->
      Array.iter
        (fun (s : Ir.Plan.loop_state) ->
           (match s.exit with
            | Ir.Plan.May_exit -> ()
            | Ir.Plan.May_exit_reporting id -> note id);
           Option.iter (fun (m : Ir.Plan.missing) -> note m.message) s.when_missing;
           instr s.emits)
        l.states
  in
  Array.iter (fun (r : Ir.Plan.rule) -> instr r.body) p.rules;
  Array.iter
    (fun (b : Ir.Plan.block) ->
       note b.message;
       Array.iter (fun (q : Ir.Plan.postfix) -> instr q.body) b.postfix)
    p.blocks;
  seen
;;

(* One tally per plan form. A form the corpus never lowers to is a form no
   grammar reaches. *)
let built : (string, int) Hashtbl.t = Hashtbl.create 32

let saw (name : string) : unit =
  Hashtbl.replace built name (1 + Option.value (Hashtbl.find_opt built name) ~default:0)
;;

let forms =
  [ "seq"
  ; "open"
  ; "close"
  ; "trivia"
  ; "bump"
  ; "bump-reporting"
  ; "drain"
  ; "expect"
  ; "call"
  ; "pratt"
  ; "alt"
  ; "commit"
  ; "loop"
  ; "may-exit"
  ; "may-exit-reporting"
  ; "when-missing"
  ; "resume"
  ; "no-resume"
  ; "boundary"
  ; "postfix"
  ; "prefix"
  ; "infix"
  ; "atom-token"
  ; "atom-rule"
  ; "prefix-kind"
  ; "infix-kind"
  ]
;;

let rec tally (i : Ir.Plan.instr) =
  match i with
  | Open _ -> saw "open"
  | Close -> saw "close"
  | Trivia -> saw "trivia"
  | Bump -> saw "bump"
  | Bump_reporting _ -> saw "bump-reporting"
  | Call _ -> saw "call"
  | Pratt _ -> saw "pratt"
  | Drain _ -> saw "drain"
  | Expect _ -> saw "expect"
  | Seq xs ->
    saw "seq";
    Array.iter tally xs
  | Alt a ->
    saw "alt";
    Array.iter (fun (_, body) -> tally body) a.arms;
    tally a.otherwise
  | Commit c ->
    saw "commit";
    saw (if c.resume = None then "no-resume" else "resume");
    tally c.body
  | Loop l ->
    saw "loop";
    Array.iter
      (fun (s : Ir.Plan.loop_state) ->
         (match s.exit with
          | Ir.Plan.May_exit -> saw "may-exit"
          | Ir.Plan.May_exit_reporting _ -> saw "may-exit-reporting");
         if s.when_missing <> None then saw "when-missing";
         tally s.emits)
      l.states
;;

let tally_plan (p : Ir.Plan.t) =
  Array.iter
    (fun (r : Ir.Plan.rule) ->
       if r.boundary then saw "boundary";
       tally r.body)
    p.rules;
  Array.iter
    (fun (b : Ir.Plan.block) ->
       if b.prefix_kind <> None then saw "prefix-kind";
       if b.infix_kind <> None then saw "infix-kind";
       if Array.length b.prefix > 0 then saw "prefix";
       if Array.length b.infix > 0 then saw "infix";
       Array.iter
         (fun (q : Ir.Plan.postfix) ->
            saw "postfix";
            tally q.body)
         b.postfix;
       Array.iter
         (fun (_, atom) ->
            match atom with
            | Ir.Plan.Atom_token -> saw "atom-token"
            | Ir.Plan.Atom_rule _ -> saw "atom-rule")
         b.atoms)
    p.blocks
;;

let () =
  let checked = ref 0 in
  let entries = ref 0 in
  List.iter
    (fun (name, g) ->
       match Core.Facts.of_grammar g with
       | Error _ -> Law.fail "%s: the grammar does not check" name
       | Ok f ->
         let plan, msgs = Plan.Lower.of_facts f in
         incr checked;
         tally_plan plan;
         entries := !entries + Plan.Messages.count msgs;
         (match Plan.Check.run plan with
          | Ok () -> ()
          | Error problems ->
            List.iter
              (fun p -> Law.fail "(a) %s: %a" name Plan.Check.pp_problem p)
              problems);
         let named = ids_in plan in
         let n = Plan.Messages.count msgs in
         Hashtbl.iter
           (fun id () ->
              if id < 0 || id >= n
              then
                Law.fail
                  "(b) %s names the message %d, and the catalogue holds %d"
                  name
                  id
                  n)
           named;
         for id = 0 to n - 1 do
           if not (Hashtbl.mem named id)
           then
             Law.fail
               "(c) %s: nothing in the plan names the message %d, %S"
               name
               id
               (Plan.Messages.text msgs (Ir.Message.of_int id))
         done)
    corpus;
  if Law.failures () = 0
  then
    Law.pass
      "every lowering checks, and its plan and catalogue agree, over %d grammars and %d \
       entries"
      !checked
      !entries
;;

let () =
  match List.filter (fun n -> not (Hashtbl.mem built n)) forms with
  | [] ->
    Law.pass
      "every plan form is one a grammar reaches (%s)"
      (String.concat
         " "
         (List.map (fun n -> Printf.sprintf "%s %d" n (Hashtbl.find built n)) forms))
  | missing ->
    Law.fail
      "(d) no grammar lowers to %s, so nothing in the corpus needs it"
      (String.concat ", " missing)
;;

(* -- (e) every kind is checked where it sits ------------------------------- *)

(* [Check.run] looks in forty-two places and names fourteen problems, and
   test/laws/law_plan.ml gives it one broken plan per problem. That is not the
   same claim. A plan carrying a negative kind proves the checker can say
   [Negative_kind]; it says nothing about whether the checker looks for one
   inside an [Open], or a [Commit]'s placeholder, or a block's hole. Delete any
   single one of those tests and the plan aimed at the problem still produces it
   from somewhere else.

   Thirty-eight mutations to check.ml survived the suite before this part
   existed, one per site, which is what that gap looks like from outside.

   So the broken plans here are derived rather than written. The walk visits
   every kind in a real plan and gives back one plan per kind with that kind
   negated, named by where it sat. A field added to [Ir.Plan] is covered the day
   it appears, and nobody has to remember a case.

   The order the walk visits in is whatever the compiler evaluates a record in,
   which is unspecified and consistent. Nothing here needs it to be left to
   right: a name is taken at the moment a kind is reached, so it belongs to the
   kind it names however they are ordered. *)
let negate ~(target : int) (p : Ir.Plan.t) : Ir.Plan.t * int * string =
  let seen = ref 0 in
  let hit = ref "" in
  let kind (at : string) (k : Ir.Kind.t) : Ir.Kind.t =
    let i = !seen in
    incr seen;
    if i = target
    then (
      hit := at;
      -1)
    else k
  in
  let kinds (at : string) (ks : Ir.Kind.t array) : Ir.Kind.t array =
    Array.mapi (fun i k -> kind (Printf.sprintf "%s/%d" at i) k) ks
  in
  let opt_kind (at : string) (k : Ir.Kind.t option) : Ir.Kind.t option =
    Option.map (kind at) k
  in
  let rec instr (at : string) (i : Ir.Plan.instr) : Ir.Plan.instr =
    match i with
    | Ir.Plan.Seq xs ->
      Ir.Plan.Seq (Array.mapi (fun n x -> instr (Printf.sprintf "%s/%d" at n) x) xs)
    | Ir.Plan.Open k -> Ir.Plan.Open (kind (at ^ "/open") k)
    | Ir.Plan.Close
    | Ir.Plan.Trivia
    | Ir.Plan.Bump
    | Ir.Plan.Bump_reporting _
    | Ir.Plan.Drain _ -> i
    | Ir.Plan.Expect e ->
      let tok = kind (at ^ "/expect tok") e.tok in
      let hole = opt_kind (at ^ "/expect hole") e.hole in
      let placeholder = opt_kind (at ^ "/expect placeholder") e.placeholder in
      Ir.Plan.Expect { e with tok; hole; placeholder }
    | Ir.Plan.Call _ | Ir.Plan.Pratt _ -> i
    | Ir.Plan.Alt a ->
      Ir.Plan.Alt
        { arms =
            Array.mapi
              (fun n (on, body) ->
                 let at = Printf.sprintf "%s/arm %d" at n in
                 let on = kinds at on in
                 on, instr at body)
              a.arms
        ; otherwise = instr (at ^ "/otherwise") a.otherwise
        }
    | Ir.Plan.Commit c ->
      let first = kinds (at ^ "/first") c.first in
      let recover = kinds (at ^ "/recover") c.recover in
      let hole = opt_kind (at ^ "/hole") c.hole in
      let placeholder = kind (at ^ "/placeholder") c.placeholder in
      let resume = Option.map (kinds (at ^ "/resume")) c.resume in
      let body = instr (at ^ "/body") c.body in
      Ir.Plan.Commit { c with first; recover; hole; placeholder; resume; body }
    | Ir.Plan.Loop l ->
      let ends_on = Option.map (kinds (at ^ "/ends-on")) l.ends_on in
      let states =
        Array.mapi
          (fun si (st : Ir.Plan.loop_state) ->
             let at = Printf.sprintf "%s/state %d" at si in
             let accepts =
               Array.mapi
                 (fun ai (on, goto) ->
                    kinds (Printf.sprintf "%s/accepts %d" at ai) on, goto)
                 st.accepts
             in
             let when_missing =
               Option.map
                 (fun (m : Ir.Plan.missing) ->
                    { m with tok = kind (at ^ "/missing") m.tok })
                 st.when_missing
             in
             let emits = instr (at ^ "/emits") st.emits in
             { st with accepts; when_missing; emits })
          l.states
      in
      Ir.Plan.Loop { l with ends_on; states }
  in
  let rules =
    Array.mapi
      (fun ri (r : Ir.Plan.rule) ->
         let at = Printf.sprintf "rule %d %s" ri r.name in
         let kind' = kind (at ^ "/kind") r.kind in
         let first = kinds (at ^ "/first") r.first in
         let adds = kinds (at ^ "/adds") r.adds in
         let body = instr at r.body in
         { r with kind = kind'; first; adds; body })
      p.rules
  in
  let blocks =
    Array.mapi
      (fun bi (b : Ir.Plan.block) ->
         let at = Printf.sprintf "block %d" bi in
         let base_kind = kind (at ^ "/base") b.base_kind in
         let prefix_kind = opt_kind (at ^ "/prefix kind") b.prefix_kind in
         let infix_kind = opt_kind (at ^ "/infix kind") b.infix_kind in
         let hole_kind = kind (at ^ "/hole") b.hole_kind in
         let expected = kinds (at ^ "/expected") b.expected in
         let infix =
           Array.mapi
             (fun i (t, bp) -> kind (Printf.sprintf "%s/infix %d" at i) t, bp)
             b.infix
         in
         let prefix =
           Array.mapi
             (fun i (t, bp) -> kind (Printf.sprintf "%s/prefix %d" at i) t, bp)
             b.prefix
         in
         let atoms =
           Array.mapi
             (fun ai (on, atom) -> kinds (Printf.sprintf "%s/atom %d" at ai) on, atom)
             b.atoms
         in
         let postfix =
           Array.mapi
             (fun pi (q : Ir.Plan.postfix) ->
                let at = Printf.sprintf "%s/postfix %d" at pi in
                let lead = kind (at ^ "/lead") q.lead in
                let kind' = kind (at ^ "/kind") q.kind in
                let body = instr at q.body in
                { q with lead; kind = kind'; body })
             b.postfix
         in
         { b with
           base_kind
         ; prefix_kind
         ; infix_kind
         ; hole_kind
         ; expected
         ; infix
         ; prefix
         ; atoms
         ; postfix
         })
      p.blocks
  in
  let pairs =
    Array.mapi
      (fun i (o, c) ->
         let at = Printf.sprintf "pairs %d" i in
         let o = kind (at ^ "/open") o in
         let c = kind (at ^ "/close") c in
         o, c)
      p.pairs
  in
  let trivia = kinds "trivia" p.trivia in
  let error_kind = kind "error kind" p.error_kind in
  let missing_kind = kind "missing kind" p.missing_kind in
  { p with rules; blocks; pairs; trivia; error_kind; missing_kind }, !seen, !hit
;;

let () =
  let sites = ref 0 in
  let missed = ref [] in
  List.iter
    (fun (name, g) ->
       match Core.Facts.of_grammar g with
       | Error _ -> ()
       | Ok f ->
         let plan, _ = Plan.Lower.of_facts f in
         let _, total, _ = negate ~target:(-1) plan in
         sites := !sites + total;
         for i = 0 to total - 1 do
           let broken, _, where = negate ~target:i plan in
           let caught =
             match Plan.Check.run broken with
             | Ok () -> false
             | Error problems ->
               List.exists
                 (fun (problem : Plan.Check.problem) ->
                    match problem with
                    | Plan.Check.Negative_kind _ -> true
                    | _ -> false)
                 problems
           in
           if not caught then missed := Printf.sprintf "%s %s" name where :: !missed
         done)
    corpus;
  match List.rev !missed with
  | [] ->
    Law.pass "(e) a negative kind is reported wherever one can sit, over %d places" !sites
  | wheres ->
    List.iter (fun w -> Law.fail "(e) a negative kind at %s is not reported" w) wheres
;;

(* -- (f) every index and every dispatch set is checked where it sits ------- *)

(* Part (e) for the plan's indices and dispatch sets. [Check.run] tests an
   index against the array it points into in eight places, and reports a
   dispatch entry with no kinds in three. One broken plan per problem leaves
   the gap part (e) closes: delete one of those tests and the plan aimed at
   the problem still produces it from another.

   Each index is tried at four values. At -1 and at the array's length the
   checker has to report it. At 0 and at the last index it must report
   nothing about it, and must not raise. A test written one step too tight
   reports a good index, and one written one step too loose reads past the
   end of the array. *)
type index_site =
  { at : string
  ; bound : int
  ; is_it : Plan.Check.problem -> bool
  }

let rule_out_of_range : Plan.Check.problem -> bool = function
  | Plan.Check.Rule_out_of_range _ -> true
  | _ -> false
;;

let block_out_of_range : Plan.Check.problem -> bool = function
  | Plan.Check.Block_out_of_range _ -> true
  | _ -> false
;;

let state_out_of_range : Plan.Check.problem -> bool = function
  | Plan.Check.Loop_state_out_of_range _ -> true
  | _ -> false
;;

(* The plan with every index passed through [index] and every dispatch set
   through [dispatch]. *)
let map_sites
      ~(index : index_site -> int -> int)
      ~(dispatch : string -> Ir.Kind.t array -> Ir.Kind.t array)
      (p : Ir.Plan.t)
  : Ir.Plan.t
  =
  let n_rules = Array.length p.rules in
  let n_blocks = Array.length p.blocks in
  let rule_index (at : string) (r : int) : int =
    index { at; bound = n_rules; is_it = rule_out_of_range } r
  in
  let rec instr (at : string) (i : Ir.Plan.instr) : Ir.Plan.instr =
    match i with
    | Ir.Plan.Seq xs ->
      Ir.Plan.Seq (Array.mapi (fun n x -> instr (Printf.sprintf "%s/%d" at n) x) xs)
    | Ir.Plan.Open _
    | Ir.Plan.Close
    | Ir.Plan.Trivia
    | Ir.Plan.Bump
    | Ir.Plan.Bump_reporting _
    | Ir.Plan.Drain _
    | Ir.Plan.Expect _ -> i
    | Ir.Plan.Call r -> Ir.Plan.Call (rule_index (at ^ "/call") r)
    | Ir.Plan.Pratt b ->
      let block =
        index { at = at ^ "/pratt"; bound = n_blocks; is_it = block_out_of_range } b.block
      in
      Ir.Plan.Pratt { b with block }
    | Ir.Plan.Alt a ->
      Ir.Plan.Alt
        { arms =
            Array.mapi
              (fun n (on, body) ->
                 let at = Printf.sprintf "%s/arm %d" at n in
                 dispatch at on, instr at body)
              a.arms
        ; otherwise = instr (at ^ "/otherwise") a.otherwise
        }
    | Ir.Plan.Commit c -> Ir.Plan.Commit { c with body = instr (at ^ "/body") c.body }
    | Ir.Plan.Loop l ->
      let n = Array.length l.states in
      let state_index (at : string) (state : int) : int =
        index { at; bound = n; is_it = state_out_of_range } state
      in
      let entry = state_index (at ^ "/entry") l.entry in
      let states =
        Array.mapi
          (fun si (st : Ir.Plan.loop_state) ->
             let at = Printf.sprintf "%s/state %d" at si in
             let accepts =
               Array.mapi
                 (fun ai (on, goto) ->
                    let at = Printf.sprintf "%s/accepts %d" at ai in
                    dispatch at on, state_index (at ^ "/goto") goto)
                 st.accepts
             in
             let when_missing =
               Option.map
                 (fun (m : Ir.Plan.missing) ->
                    { m with goto = state_index (at ^ "/missing goto") m.goto })
                 st.when_missing
             in
             let emits = instr (at ^ "/emits") st.emits in
             { st with accepts; when_missing; emits })
          l.states
      in
      Ir.Plan.Loop { l with entry; states }
  in
  let rules =
    Array.mapi
      (fun ri (r : Ir.Plan.rule) ->
         { r with body = instr (Printf.sprintf "rule %d %s" ri r.name) r.body })
      p.rules
  in
  let blocks =
    Array.mapi
      (fun bi (b : Ir.Plan.block) ->
         let at = Printf.sprintf "block %d" bi in
         let atoms =
           Array.mapi
             (fun ai (on, atom) ->
                let at = Printf.sprintf "%s/atom %d" at ai in
                let atom =
                  match atom with
                  | Ir.Plan.Atom_token -> atom
                  | Ir.Plan.Atom_rule r -> Ir.Plan.Atom_rule (rule_index at r)
                in
                dispatch at on, atom)
             b.atoms
         in
         let postfix =
           Array.mapi
             (fun pi (q : Ir.Plan.postfix) ->
                { q with body = instr (Printf.sprintf "%s/postfix %d" at pi) q.body })
             b.postfix
         in
         { b with atoms; postfix })
      p.blocks
  in
  let roots = Array.mapi (fun i r -> rule_index (Printf.sprintf "root %d" i) r) p.roots in
  { p with rules; blocks; roots }
;;

(* The plan with the index at [target] set to [value] of its bound, the number
   of index sites, and the site the index sat at. *)
let reindex ~(target : int) ~(value : int -> int) (p : Ir.Plan.t)
  : Ir.Plan.t * int * index_site option
  =
  let seen = ref 0 in
  let hit = ref None in
  let plan =
    map_sites
      p
      ~dispatch:(fun _ on -> on)
      ~index:(fun site i ->
        let n = !seen in
        incr seen;
        if n = target
        then (
          hit := Some site;
          value site.bound)
        else i)
  in
  plan, !seen, !hit
;;

(* The plan with the dispatch set at [target] emptied, the number of
   dispatch sets, and where the emptied one sat. *)
let empty_dispatch ~(target : int) (p : Ir.Plan.t) : Ir.Plan.t * int * string =
  let seen = ref 0 in
  let hit = ref "" in
  let plan =
    map_sites
      p
      ~index:(fun _ i -> i)
      ~dispatch:(fun at on ->
        let n = !seen in
        incr seen;
        if n = target
        then (
          hit := at;
          [||])
        else on)
  in
  plan, !seen, !hit
;;

let () =
  let index_sites = ref 0 in
  let dispatch_sites = ref 0 in
  let missed = ref [] in
  let miss (what : string) = missed := what :: !missed in
  (* The value an index is set to, how it reads in a failure, and whether the
     checker has to report it. *)
  let values =
    [ (fun (_ : int) -> -1), "-1", true
    ; (fun (bound : int) -> bound), "its length", true
    ; (fun (_ : int) -> 0), "0", false
    ; (fun (bound : int) -> bound - 1), "its last index", false
    ]
  in
  List.iter
    (fun (name, g) ->
       match Core.Facts.of_grammar g with
       | Error _ -> ()
       | Ok f ->
         let plan, _ = Plan.Lower.of_facts f in
         let _, total, _ = reindex ~target:(-1) ~value:Fun.id plan in
         index_sites := !index_sites + total;
         for i = 0 to total - 1 do
           List.iter
             (fun (value, says, reported) ->
                match reindex ~target:i ~value plan with
                | _, _, None -> ()
                | broken, _, Some site ->
                  let where = Printf.sprintf "%s %s set to %s" name site.at says in
                  (match Plan.Check.run broken with
                   | exception e ->
                     miss (Printf.sprintf "%s raised %s" where (Printexc.to_string e))
                   | Ok () -> if reported then miss (where ^ " is not reported")
                   | Error problems ->
                     let found = List.exists site.is_it problems in
                     if reported && not found then miss (where ^ " is not reported");
                     if found && not reported then miss (where ^ " is reported")))
             values
         done;
         let _, total, _ = empty_dispatch ~target:(-1) plan in
         dispatch_sites := !dispatch_sites + total;
         for i = 0 to total - 1 do
           let broken, _, at = empty_dispatch ~target:i plan in
           let where = Printf.sprintf "%s %s emptied" name at in
           match Plan.Check.run broken with
           | exception e ->
             miss (Printf.sprintf "%s raised %s" where (Printexc.to_string e))
           | Ok () -> miss (where ^ " is not reported")
           | Error problems ->
             if
               not
                 (List.exists
                    (fun (problem : Plan.Check.problem) ->
                       match problem with
                       | Plan.Check.Empty_arm _ -> true
                       | _ -> false)
                    problems)
             then miss (where ^ " is not reported")
         done)
    corpus;
  match List.rev !missed with
  | [] ->
    Law.pass
      "(f) every index is checked at both ends over %d places, and every empty dispatch \
       is reported over %d"
      !index_sites
      !dispatch_sites
  | wheres -> List.iter (fun w -> Law.fail "(f) %s" w) wheres
;;

let () = Law.summarise "law_lower"
