(* -- every rejection is deserved ----------------------------------------------

      (a) For every code in [Error.codes] there is a witness grammar that
          provokes that code and no other.
      (b) [Error.codes] lists every code the checker emits: no witness
          produces one outside it.
      (c) Every check runs at the stage its code is filed under in
          [Error.codes_by_stage].
      (d) Every grammar in the accepted corpus yields a [Facts.t].
      (e) Findings come back sorted and free of duplicates.
      (f) One left-recursive cycle is one finding, whatever its length.

      Mechanism: an oracle over the witness corpus, with no baseline. Part (c)
      is a cross-check between the stage a code is filed under and the stage
      that emits it.

      Why each part is separate from the others. Part (a) compares sets of
      codes, so a check that reports one code k times collapses to the same set
      and (a) stays green; part (f) carries the count for that reason. Part (c)
      cross-checks the stage a code is filed under against the stage that emits
      it, so a check moved from one stage to another passes (a) and fails (c).
      Part (e) rejects findings that are identical, which a left recursion
      reported per member is not: the members differ in their site and message.
      Each part exists because the one beside it cannot see something.

      Why three witnesses carry [~greedy:true]. Each uses the flag to keep a
      FIRST/FOLLOW complaint quiet so that its own code is the only one it
      reports. Drop the guard that reads the flag and those three report two
      codes apiece, and each of part (f)'s six cycles reports a conflict beside
      the recursion.

      Where a collision is recorded. The duplicate-child-name witness lives
      here rather than under test/laws/law_manifest.ml, because that law reads
      the manifest for the collision and finds it either way. This one reads
      whether the checker refused the grammar.

      The one test with a blast radius. Dropping the self-edge test on a
      one-rule component makes every rule a component of its own, so every
      grammar in the tree is rejected: 21 findings here, 15 in law_facts, 10
      each in law_first_follow and law_manifest, and one apiece from sexp_facts
      and pratt_desugar, because each needs a [Facts.t] the checker now refuses
      to build. That one test is what separates a rule from a rule that reaches
      itself.

      Why (c) is separate from (a). A check that moves stage keeps its witness
      rejected, so (a) still passes: the grammar is refused, just not where the
      code says it is refused. (c) is the part that reads the stage.

      Coverage. The 54 witness grammars and the 10 accepted ones: at least
      one grammar per rejection and a handful of near misses, together with
      the six cycles part (f) builds for itself. It says nothing about whether
      a check's reason is right, only that it fires on one shape and stays
      quiet on ten others. Ten accepted grammars is a statement about ten
      grammars; a generated corpus is what would make it a statement about
      the checker.
   -------------------------------------------------------------------------- *)

(* The four blocks below are generated, and they are the evidence. assay
   derives a mutation from the code rather than from a sentence beside it,
   applies every one, and records what went red. Regenerate them with

     assay -config assay.conf -only core

   and take the counts as they come: they move whenever the corpus grows, and
   asserting them exactly would train everyone to ignore a red suite. What they
   assert is that every mutant dies. A survivor is the finding, and the lines it
   names are where to look. *)

(* -- mutation testing, generated by assay on 2026-10-01 ---------------------
      lib/core/check_names.ml, 57 mutants, 55 killed, 2 survived.
        extreme     14  all killed, law_validate invalid-name:: 8, law_lower rust:: 2, law_validate empty-grammar:: 2, law_validate postfix-suffix-missing:: 1, law_validate unknown-delimiter-token:: 1
        sbr         10  all killed, dup-kind-name: 1 dup-pratt-op: 1 dup-root: 1 invalid-token-literal: 1 mixed-assoc-at-bp: 1 no-roots: 1 nullable-token: 1 postfix-suffix-duplicate: 1 unknown-op-token: 1 unknown-rule: 1
        ror         12  all killed, law_lower calc:: 3, law_lower sexp:: 3, law_validate dup-kind-name:: 2, law_validate postfix-suffix-missing:: 2, law_lower postfix:: 1, law_validate invalid-name:: 1
        lcr          2  1 killed, calc: 1; 1 survived
        aor          1  0 killed; 1 survived
        uoi         18  all killed, law_lower calc:: 6, law_lower sexp:: 6, law_lower postfix:: 2, law_validate dup-kind-name:: 2, law_validate invalid-name:: 1, law_validate postfix-suffix-missing:: 1
      survived at lines 110 553
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-01 ---------------------
      lib/core/check_shape.ml, 23 mutants, 21 killed, 2 survived.
        extreme      6  4 killed, unused-resync-anchors: 3 delimited-arity: 1; 2 survived
        sbr          4  all killed, repeated-vs-single: 2 delimited-arity: 1 unused-resync-anchors: 1
        ror          6  all killed, law_lower ml:: 2, law_lower sexp:: 2, law_lower shapes:: 1, law_validate repeated-vs-single:: 1
        lcr          1  all killed, sexp: 1
        uoi          6  all killed, law_lower sexp:: 2, law_lower comments:: 1, law_lower json:: 1, law_lower ml:: 1, law_validate repeated-vs-single:: 1
      survived at lines 20 24
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-01 ---------------------
      lib/core/check_full.ml, 138 mutants, 104 killed, 33 survived, 1 timed out.
        extreme     13  12 killed, first-first-conflict: 12; 1 survived
        sbr         52  36 killed, law_validate left-recursion:: 13, law_validate empty-first-set:: 5, law_validate first-follow-conflict:: 5, law_lower sexp:: 3, law_validate token-unreachable:: 3, law_lower: 1, law_validate: 1, law_validate nullable-pratt-atom:: 1, law_validate nullable-repeated:: 1, law_validate pratt-atom-conflict:: 1, law_validate prefix-atom-conflict:: 1, law_validate resync-anchor-conflict:: 1; 15 survived; 1 timed out
        ror         22  12 killed, law_lower: 2, law_validate first-first-conflict:: 2, law_lower rust:: 1, law_lower sexp:: 1, law_validate empty-first-set:: 1, law_validate left-recursion:: 1, law_validate nullable-repeated:: 1, law_validate pratt-atom-conflict:: 1, law_validate prefix-atom-conflict:: 1, law_validate token-unreachable:: 1; 10 survived
        lcr          7  5 killed, law_lower sexp:: 3, law_lower: 2; 2 survived
        aor          7  all killed, law_lower: 6, law_lower sexp:: 1
        uoi         34  30 killed, law_lower: 7, law_lower sexp:: 7, law_lower calc:: 3, law_validate left-recursion:: 3, law_lower rust:: 2, law_lower shapes:: 1, law_validate: 1, law_validate empty-first-set:: 1, law_validate first-first-conflict:: 1, law_validate nullable-repeated:: 1, law_validate pratt-atom-conflict:: 1, law_validate prefix-atom-conflict:: 1, law_validate token-unreachable:: 1; 4 survived
        empty        3  2 killed, first-first-conflict: 1 pratt-atom-conflict: 1; 1 survived
      survived at lines 10 77 84 93 113 176 180 182 185 219 233 239 323 339 360 385 387 388 393 397 401 474 508 509 516 518
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-01 ---------------------
      lib/core/error.ml, 62 mutants, 52 killed, 10 survived.
        extreme     11  1 killed, empty-grammar: 1; 10 survived
        sbr         51  all killed, ambiguous-same-kind-child 2 binder-not-pattern-token 2 empty-first-set 2 delimited-arity 1 dup-child-name 1 dup-kind-name 1 dup-pratt-op 1 dup-root 1 empty-grammar 1 empty-pratt-atoms 1 first-first-conflict 1 first-follow-conflict 1 invalid-name 1 invalid-token-literal 1 left-recursion 1 mixed-assoc-at-bp 1 mixed-pratt-role 1 name-collision 1 no-roots 1 nullable-pratt-atom 1 nullable-repeated 1 nullable-separated-element 1 nullable-token 1 overlapping-single-kinds 1 postfix-suffix-duplicate 1 postfix-suffix-missing 1 pratt-atom-conflict 1 prefix-atom-conflict 1 repeated-vs-single 1 repeated-vs-single-kinds 1 reserved-name 1 resync-anchor-conflict 1 root-is-block 1 separated-arity 1 token-unreachable 1 unknown-binder-child 1 unknown-delimiter-token 1 unknown-identity-child 1 unknown-message-child 1 unknown-op-token 1 unknown-recover-to-token 1 unknown-resync-anchor 1 unknown-root 1 unknown-rule 1 unknown-token 1 unused-message-child 1 unused-recover-to 1 unused-resync-anchors 1
      survived at lines 30 271 279 285 287 323 524 567 577 593
   ---------------------------------------------------------------------- *)

let codes_of = function
  | Ok _ -> []
  | Error es ->
    List.sort_uniq
      String.compare
      (List.map (fun (e : Core.Error.t) -> Core.Error.code e) es)
;;

let stage_of_code (code : string) : string option =
  List.find_map
    (fun (stage, cs) -> if List.mem code cs then Some stage else None)
    Core.Error.codes_by_stage
;;

(* (a) and (b) *)
let () =
  List.iter
    (fun (code, g) ->
       match codes_of (Core.Facts.of_grammar g) with
       | [] -> Law.fail "%s: the witness grammar was accepted" code
       | [ c ] when c = code -> Law.pass "%s: witness provokes exactly it" code
       | cs ->
         Law.fail
           "%s: witness provokes {%s} instead of exactly it"
           code
           (String.concat ", " cs))
    Lingo_witness.Witnesses.all
;;

let () =
  let witnessed =
    List.sort_uniq String.compare (List.map fst Lingo_witness.Witnesses.all)
  in
  let declared = List.sort_uniq String.compare Core.Error.codes in
  List.iter
    (fun c ->
       if not (List.mem c witnessed)
       then
         Law.fail
           "%s is in Error.codes but has no witness: it is untested or unreachable, and \
            both are findings"
           c)
    declared;
  List.iter
    (fun c ->
       if not (List.mem c declared) then Law.fail "%s is emitted but not in Error.codes" c)
    witnessed;
  if List.length Core.Error.codes <> List.length declared
  then Law.fail "Error.codes contains a duplicate";
  List.iter
    (fun c ->
       if stage_of_code c = None
       then Law.fail "%s is in Error.codes but in no stage list" c)
    declared;
  if Law.failures () = 0
  then Law.pass "Error.codes and the witness table are the same set"
;;

(* (c). The one caller of [Internal]. A code filed under "names" and caught
   at the third stage passes the completeness law while reporting two
   derivations later than it could, and running the stages one at a time is
   how that shows. *)

let () =
  List.iter
    (fun (code, g) ->
       let declared = Option.get (stage_of_code code) in
       let n = Core.Internal.Stage.names g in
       let s1 = Core.Internal.Check_names.run n in
       let observed =
         if s1 <> []
         then "names"
         else (
           let shape = Core.Internal.Stage.shape n in
           if Core.Internal.Check_shape.run shape <> []
           then "shape"
           else if
             Core.Internal.Check_full.run
               shape
               (Core.Internal.Fixpoint.compute
                  ~rules:shape.rules
                  ~blocks:shape.blocks
                  ~kind_rule:shape.names.kind_rule)
               (Core.Internal.Stage.lexer n)
             <> []
           then "full"
           else "accepted")
       in
       if observed = declared
       then Law.pass "%s: rejected at stage %s, as filed" code declared
       else Law.fail "%s: filed under stage %s but rejected at %s" code declared observed)
    Lingo_witness.Witnesses.all
;;

(* (e). Several checks build their reports by folding a hash table, so the
   sort is what fixes the order a caller sees. *)
let () =
  List.iter
    (fun (code, g) ->
       match Core.Facts.of_grammar g with
       | Ok _ -> ()
       | Error es ->
         if List.sort Core.Error.compare es <> es
         then Law.fail "%s: findings are not sorted" code
         else if List.sort_uniq Core.Error.compare es <> es
         then Law.fail "%s: findings contain a duplicate" code)
    Lingo_witness.Witnesses.all;
  if Law.failures () = 0 then Law.pass "findings are sorted and duplicate-free"
;;

(* (d) *)
let () =
  List.iter
    (fun (name, g) ->
       match Core.Facts.of_grammar g with
       | Ok _ -> Law.pass "accepted: %s" name
       | Error es ->
         Law.fail
           "accepted corpus grammar %s was rejected:@\n%a"
           name
           Core.Error.pp_list
           es)
    Lingo_witness.Witnesses.accepted
;;

(* (f). The property is about the length of the cycle and the witness table
   fixes two lengths, so these are built here and quantified over. A cycle of
   one is the length at which reporting rotations and reporting components
   agree, which is why the corpus on its own could not separate them. *)
let () =
  let name i = Printf.sprintf "P%d" i in
  let cycle n =
    Grammar.create
      ~tokens:[ Grammar.punct_tight ~name:"ta" "a" ]
      ~roots:[ name 0 ]
      (List.init n (fun i ->
         Grammar.prod
           (name i)
           [ Grammar.child_opt ~greedy:true "l" (Grammar.Rule (name ((i + 1) mod n)))
           ; Grammar.child_req "t" (Grammar.Token "ta")
           ]))
  in
  List.iter
    (fun n ->
       match Core.Facts.of_grammar (cycle n) with
       | Ok _ -> Law.fail "a cycle of %d rules was accepted" n
       | Error es ->
         let mine =
           List.filter (fun (e : Core.Error.t) -> Core.Error.code e = "left-recursion") es
         in
         if List.length es <> 1 || List.length mine <> 1
         then
           Law.fail
             "a cycle of %d rules reports %d findings, %d of them left-recursion: one \
              cycle is one left recursion"
             n
             (List.length es)
             (List.length mine))
    [ 1; 2; 3; 4; 5; 8 ];
  if Law.failures () = 0
  then Law.pass "one left recursion is one finding, at every cycle length"
;;

let () = Law.summarise "law_validate"
