(* -- the plan IR --------------------------------------------------------------

      (a) [parse] reads what [pp] wrote, and gets the same plan back.
      (b) [pp] is deterministic at a fixed width, and printing a plan read
          back gives the same bytes.
      (c) [check] accepts a well-formed plan, and reports each malformed one
          with the problem that names what is wrong.

      Mechanism. All three are oracles over one plan built by hand, which
      reaches every instruction, every postfix body and every atom form. A
      round trip over a plan holding three of them would say nothing about
      the rest, so a new instruction goes in this plan.

      Part (c) works over a deliberately broken plan per thing the checker
      can report, and more than one where a problem has several sources.
      Each is the good plan with one thing changed, so the finding is
      attributable.

      Part (a)'s oracle is not a second printer. It reads the text back into
      a plan and compares the plans, so a field the printer drops and the
      reader defaults would have to be dropped and defaulted to the same
      value to stay hidden.

      Coverage. One plan, and twenty-six broken ones. The plan's loop reaches
      both exit policies: it may end after an element, and ending after a
      separator reports the separator as extra. The round-trip says
      nothing about a plan no [of_facts] would build, and [of_facts] does not
      exist yet: the goldens over the example grammars land with it. It is
      stated over plans that pass [check], because an empty [resume] set and
      [resume = None] print the same and [check] is what rules the first one
      out.

      Reaching every form is not the same as reaching every value. The plan
      once carried only plain names, so the printer and the reader disagreed
      about escaping and the round-trip stayed green. One child name now
      carries every character the printer escapes, and one that it does not:
      a quote, a backslash, the three named whitespace escapes, a byte below
      32, byte 127, and a byte above 127 that goes out as it stands.

      Why the round trip runs both ways. A printer that puts a commit's
      [recover] set where its [first] set goes, or writes a reporting exit as a
      bare [may], produces output that still parses. The plans differ and a
      check on the reader alone would see nothing, so the law compares the plan
      that came back with the plan that went out.

      Why the corpus looks the way it does. One child name carries spaces, so a
      printer that quoted nothing would have the reader take it as three atoms.
      The same name holds a byte below 32 and byte 127, which the printer has no
      other way to write than as an escape. And one plan is hand-edited with
      comments in it, because a printed plan carries none and nothing else would
      reach the reader's comment branch.

      Why part (c) counts six cascades. An [Alt]'s arms, a loop state's accepts,
      and a block's atoms, infix, prefix and postfix tables are separate
      dispatches, and a token may sit in more than one of them. One cascade
      shared between them would report an overlap that is not there.

      Why depth is two numbers. A branch whose opens and closes come to nothing
      overall can still close a node it never opened, so the net depth is not
      enough on its own and the lowest depth the branch passed through is
      carried beside it.

      One thing the printer does for a reader rather than for correctness.
      Quoting with [%S] would write a byte above 127 as [\ddd], and the reader
      takes that form too, so the two agree either way and no mutation of it
      reddens anything. The printer writes such a byte as itself so that a name
      in UTF-8 appears in a dump as itself rather than as a run of escapes. That
      is a claim about reading a diff.

   -------------------------------------------------------------------------- *)

(* The four blocks below are generated, and they are the evidence. assay derives
   a mutation from the code rather than from a sentence beside it, applies every
   one, and records what went red. Regenerate them with

     assay -config assay.conf -only plan

   and take the counts as they come: they move whenever the corpus grows, and
   asserting them exactly would train everyone to ignore a red suite. What they
   assert is that every mutant dies. A survivor is the finding, and the lines it
   names are where to look. *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/plan/check.ml, 130 mutants, 107 killed, 23 survived.
        sbr         71  64 killed, law_plan (c): 35, law_lower (e): 29; 7 survived
        ror         27  16 killed, law_plan check: 11, law_plan: 2, law_plan (c): 2, law_lower (a): 1; 11 survived
        lcr          9  5 killed, law_plan (c): 3, law_plan: 2; 4 survived
        aor          4  3 killed, law_plan: 2, law_plan check: 1; 1 survived
        uoi         19  all killed, law_plan check: 18, law_lower (a): 1
      survived in run (sbr 7, ror 11, lcr 4, aor)
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/plan/text.ml, 87 mutants, 87 killed.
        extreme      3  all killed, (a) 3
        sbr         83  all killed, law_plan (a): 79, dump_plan: 4
        uoi          1  all killed, (a) 1
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/plan/sexp.ml, 86 mutants, 49 killed, 22 survived, 15 timed out.
        extreme      3  all killed, (a) 3
        sbr         29  16 killed, law_plan (a): 15, law_plan: 1; 6 survived; 7 timed out
        ror         18  7 killed, dump_plan: 3, law_plan (a): 3, law_plan: 1; 10 survived; 1 timed out
        lcr          6  3 killed, law_plan: 2, law_plan (a): 1; 3 survived
        aor         19  10 killed, law_plan (a): 7, law_plan: 3; 3 survived; 6 timed out
        uoi         11  10 killed, (a) 10; 1 timed out
      survived in escaped (ror, lcr), pp_atom (aor),
        of_string (sbr 6, ror 9, lcr 2, aor 2)
   ---------------------------------------------------------------------- *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/plan/messages.ml, 2 mutants, 2 killed.
        sbr          2  all killed, dump_plan: 1, law_lower (b): 1
   ---------------------------------------------------------------------- *)

let msg n = Ir.Message.of_int n

(* -- one plan that reaches every form -------------------------------------- *)

(* Kinds are this law's own. 0 and 1 are the two a plan always names, 2 is
   trivia, 3 to 11 are tokens and 12 upwards are nodes. *)
let k_error = 0
let k_missing = 1
let k_ws = 2
let k_lparen = 3
let k_rparen = 4
let k_lbrack = 5
let k_rbrack = 6
let k_word = 7
let k_comma = 8
let k_plus = 9
let k_minus = 10
let k_dot = 11
let k_question = 12
let n_file = 13
let n_list = 14
let n_item = 15
let n_paren = 16
let n_base = 17
let n_prefix = 18
let n_infix = 19
let n_hole = 20
let n_index = 21
let n_access = 22
let n_try = 23

let expect ?at_child ?hole ?placeholder (tok : Ir.Kind.t) : Ir.Plan.instr =
  Ir.Plan.Expect { tok; message = msg 1; at_child; hole; placeholder }
;;

let file : Ir.Plan.rule =
  { name = "File"
  ; kind = n_file
  ; first = [| k_lparen |]
  ; adds = [||]
  ; boundary = false
  ; body =
      Ir.Plan.Seq
        [| Ir.Plan.Open n_file; Ir.Plan.Call 1; Ir.Plan.Drain (msg 5); Ir.Plan.Close |]
  }
;;

(* A delimited body with a separator is three positions, and they admit
   different things. The states are what say so, and this one reaches both
   exit policies: the body may end after an element, and ending after a
   separator reports the separator as extra. *)
let list_rule : Ir.Plan.rule =
  { name = "List"
  ; kind = n_list
  ; first = [| k_lparen |]
  ; adds = [| k_rparen; k_comma |]
  ; boundary = false
  ; body =
      Ir.Plan.Seq
        [| Ir.Plan.Open n_list
         ; expect k_lparen
         ; Ir.Plan.Loop
             { entry = 0
             ; ends_on = Some [| k_rparen |]
             ; states =
                 [| { accepts = [| [| k_lbrack; k_word |], 1 |]
                    ; exit = Ir.Plan.May_exit
                    ; when_missing = None
                    ; emits = Ir.Plan.Call 2
                    }
                  ; { accepts = [| [| k_comma |], 2 |]
                    ; exit = Ir.Plan.May_exit
                    ; when_missing = None
                    ; emits = Ir.Plan.Bump
                    }
                  ; { accepts = [| [| k_lbrack; k_word |], 1 |]
                    ; exit = Ir.Plan.May_exit_reporting (msg 4)
                    ; when_missing = None
                    ; emits = Ir.Plan.Call 2
                    }
                 |]
             }
         ; expect k_rparen ~placeholder:k_rparen
         ; Ir.Plan.Close
        |]
  }
;;

let item : Ir.Plan.rule =
  { name = "Item"
  ; kind = n_item
  ; first = [| k_lbrack; k_word |]
  ; adds = [| k_rbrack |]
  ; boundary = true
  ; body =
      Ir.Plan.Seq
        [| Ir.Plan.Open n_item
         ; Ir.Plan.Alt
             { arms =
                 [| ( [| k_lbrack |]
                    , Ir.Plan.Seq
                        [| expect k_lbrack
                         ; Ir.Plan.Commit
                             { first = [| k_lparen; k_word |]
                             ; recover =
                                 [| k_rbrack |]
                                 (* Every escape the printer can write, so
                                    the reader has to undo every one: a
                                    quote, a backslash, the three named
                                    whitespace escapes, a byte below 32 and
                                    byte 127 as [\ddd], and a byte above 127
                                    that goes out as it stands. Spaces are
                                    what make the whole thing need quoting. *)
                             ; at_child =
                                 "the \"inner\" expression,\nna\239vely\t\r \\ \001 \127"
                             ; message = msg 2
                             ; hole = Some n_hole
                             ; placeholder = n_hole
                             ; resume = Some [| k_rbrack |]
                             ; body = Ir.Plan.Pratt { block = 0; min_bp = 0 }
                             }
                         ; expect k_rbrack ~placeholder:k_rbrack
                        |] )
                  ; [| k_word |], Ir.Plan.Seq [| Ir.Plan.Trivia; Ir.Plan.Bump |]
                 |]
             ; otherwise = Ir.Plan.Call 3
             }
         ; Ir.Plan.Close
        |]
  }
;;

let paren : Ir.Plan.rule =
  { name = "Paren"
  ; kind = n_paren
  ; first = [| k_lparen |]
  ; adds = [| k_rparen |]
  ; boundary = false
  ; body =
      Ir.Plan.Seq
        [| Ir.Plan.Open n_paren
         ; expect k_lparen
         ; Ir.Plan.Pratt { block = 0; min_bp = 0 }
         ; expect k_rparen ~placeholder:k_rparen ~hole:n_hole ~at_child:"close"
         ; Ir.Plan.Close
        |]
  }
;;

let block : Ir.Plan.block =
  { name = "Expr"
  ; infix = [| k_plus, (10, 11) |]
  ; prefix = [| k_minus, 50 |]
  ; postfix =
      (* The three shapes a postfix body takes: an enclosed one, a child after
         the lead, and a lead that is the whole operator. *)
      [| { lead = k_lbrack
         ; bp = 90
         ; kind = n_index
         ; body =
             Ir.Plan.Seq
               [| Ir.Plan.Pratt { block = 0; min_bp = 0 }
                ; expect k_rbrack ~placeholder:k_rbrack
               |]
         }
       ; { lead = k_dot; bp = 80; kind = n_access; body = Ir.Plan.Bump }
       ; { lead = k_question; bp = 85; kind = n_try; body = Ir.Plan.Seq [||] }
      |]
  ; atoms = [| [| k_word |], Ir.Plan.Atom_token; [| k_lparen |], Ir.Plan.Atom_rule 3 |]
  ; base_kind = n_base
  ; prefix_kind = Some n_prefix
  ; infix_kind = Some n_infix
  ; hole_kind = n_hole
  ; expected = [| k_lparen; k_word |]
  ; message = msg 3
  }
;;

let good : Ir.Plan.t =
  { rules = [| file; list_rule; item; paren |]
  ; blocks = [| block |]
  ; roots = [| 0 |]
  ; pairs = [| k_lparen, k_rparen; k_lbrack, k_rbrack |]
  ; trivia = [| k_ws |]
  ; error_kind = k_error
  ; missing_kind = k_missing
  }
;;

(* -- (a) and (b) ----------------------------------------------------------- *)

let () =
  match Plan.Check.run good with
  | Error problems ->
    Law.fail
      "check rejected the good plan: %a"
      (Format.pp_print_list
         ~pp_sep:(fun f () -> Format.fprintf f "; ")
         Plan.Check.pp_problem)
      problems
  | Ok () -> Law.pass "check accepts a well-formed plan"
;;

(* [Text.pp] breaks a form that does not fit, and the width it fits to comes
   from the formatter. Fixing it here keeps part (b) about the printer. *)
let render (p : Ir.Plan.t) =
  let b = Buffer.create 4096 in
  let fmt = Format.formatter_of_buffer b in
  Format.pp_set_margin fmt 78;
  Plan.Text.pp fmt p;
  Format.pp_print_flush fmt ();
  Buffer.contents b
;;

let text = render good

let () =
  match Plan.Text.parse text with
  | Error m -> Law.fail "(a) the printer's own output did not parse: %s" m
  | Ok back when back <> good ->
    Law.fail "(a) the plan that came back is not the one printed"
  | Ok back ->
    let again = render back in
    if not (String.equal again text)
    then Law.fail "(b) printing the plan a second time gave different bytes"
    else
      Law.pass
        "a plan prints, reads back and prints the same, over %d bytes"
        (String.length text)
;;

(* A plan is read back with comments and odd whitespace in it, because a
   plan someone edits by hand has both. The printer writes neither. *)
let () =
  let edited = "; a comment\n" ^ text ^ "\n  ; and another\n" in
  match Plan.Text.parse edited with
  | Error m -> Law.fail "(a) a commented plan did not parse: %s" m
  | Ok back when back <> good ->
    Law.fail "(a) a commented plan read back as a different plan"
  | Ok _ -> Law.pass "comments and surrounding whitespace do not change what is read"
;;

(* -- (c) one broken plan per problem --------------------------------------- *)

(* Each is the good plan with one thing changed. The other three rules stay,
   so a finding names the change rather than what went missing with it. *)
let with_body (body : Ir.Plan.instr) : Ir.Plan.t =
  { good with rules = [| { file with body }; list_rule; item; paren |] }
;;

let with_file f : Ir.Plan.t = { good with rules = [| f; list_rule; item; paren |] }
let open_ body = Ir.Plan.Seq [| Ir.Plan.Open n_file; body; Ir.Plan.Close |]

let broken =
  [ ( "a call to a rule that is not there"
    , with_body (open_ (Ir.Plan.Call 99))
    , function
      | Plan.Check.Rule_out_of_range _ -> true
      | _ -> false )
  ; ( "a pratt call to a block that is not there"
    , with_body (open_ (Ir.Plan.Pratt { block = 99; min_bp = 0 }))
    , function
      | Plan.Check.Block_out_of_range _ -> true
      | _ -> false )
  ; ( "a set of kinds that repeats one"
    , with_file { file with first = [| k_lparen; k_lparen |] }
    , function
      | Plan.Check.Kinds_unordered _ -> true
      | _ -> false )
  ; ( "a negative kind"
    , with_file { file with kind = -1 }
    , function
      | Plan.Check.Negative_kind _ -> true
      | _ -> false )
  ; ( "an alt with no arms"
    , with_body (open_ (Ir.Plan.Alt { arms = [||]; otherwise = Ir.Plan.Seq [||] }))
    , function
      | Plan.Check.Empty_alt _ -> true
      | _ -> false )
  ; ( "an arm no kind can take"
    , with_body
        (open_
           (Ir.Plan.Alt { arms = [| [||], Ir.Plan.Bump |]; otherwise = Ir.Plan.Seq [||] }))
    , function
      | Plan.Check.Empty_arm _ -> true
      | _ -> false )
  ; ( "two alt arms on the same kind"
    , with_body
        (open_
           (Ir.Plan.Alt
              { arms = [| [| k_word |], Ir.Plan.Bump; [| k_word |], Ir.Plan.Bump |]
              ; otherwise = Ir.Plan.Seq [||]
              }))
    , function
      | Plan.Check.Kind_taken_twice _ -> true
      | _ -> false )
  ; ( "one loop state accepting a kind twice"
    , with_body
        (open_
           (Ir.Plan.Loop
              { entry = 0
              ; ends_on = None
              ; states =
                  [| { accepts = [| [| k_word |], 0; [| k_word |], 0 |]
                     ; exit = Ir.Plan.May_exit
                     ; when_missing = None
                     ; emits = Ir.Plan.Bump
                     }
                  |]
              }))
    , function
      | Plan.Check.Kind_taken_twice _ -> true
      | _ -> false )
  ; ( "two atoms on the same kind"
    , { good with
        blocks =
          [| { block with
               atoms =
                 [| [| k_word |], Ir.Plan.Atom_token; [| k_word |], Ir.Plan.Atom_rule 3 |]
             }
          |]
      }
    , function
      | Plan.Check.Kind_taken_twice _ -> true
      | _ -> false )
  ; ( "the same infix operator twice"
    , { good with
        blocks = [| { block with infix = [| k_plus, (10, 11); k_plus, (20, 21) |] } |]
      }
    , function
      | Plan.Check.Kind_taken_twice _ -> true
      | _ -> false )
  ; ( "the same prefix operator twice"
    , { good with blocks = [| { block with prefix = [| k_minus, 50; k_minus, 60 |] } |] }
    , function
      | Plan.Check.Kind_taken_twice _ -> true
      | _ -> false )
  ; ( "two postfix operators on the same lead"
    , { good with
        blocks =
          [| { block with
               postfix =
                 [| { lead = k_dot; bp = 80; kind = n_access; body = Ir.Plan.Bump }
                  ; { lead = k_dot; bp = 85; kind = n_try; body = Ir.Plan.Seq [||] }
                 |]
             }
          |]
      }
    , function
      | Plan.Check.Kind_taken_twice _ -> true
      | _ -> false )
  ; ( "a loop entering a state that is not there"
    , with_body
        (open_
           (Ir.Plan.Loop
              { entry = 9
              ; ends_on = None
              ; states =
                  [| { accepts = [||]
                     ; exit = Ir.Plan.May_exit
                     ; when_missing = None
                     ; emits = Ir.Plan.Bump
                     }
                  |]
              }))
    , function
      | Plan.Check.Loop_state_out_of_range _ -> true
      | _ -> false )
  ; ( "a resume set with nothing in it"
    , with_body
        (open_
           (Ir.Plan.Commit
              { first = [| k_word |]
              ; recover = [||]
              ; at_child = "x"
              ; message = msg 1
              ; hole = None
              ; placeholder = n_hole
              ; resume = Some [||]
              ; body = Ir.Plan.Bump
              }))
    , function
      | Plan.Check.Empty_resume _ -> true
      | _ -> false )
  ; ( "a commit over a choice whose otherwise takes nothing"
    , with_body
        (open_
           (Ir.Plan.Commit
              { first = [| k_lparen; k_word |]
              ; recover = [||]
              ; at_child = "x"
              ; message = msg 1
              ; hole = None
              ; placeholder = n_hole
              ; resume = None
              ; body =
                  Ir.Plan.Alt
                    { arms = [| [| k_word |], Ir.Plan.Bump |]
                    ; otherwise = Ir.Plan.Seq [||]
                    }
              }))
    , function
      | Plan.Check.Commit_matches_nothing _ -> true
      | _ -> false )
  ; ( "a commit over a call to a rule that can match nothing"
    , { good with
        rules =
          [| { file with
               body =
                 open_
                   (Ir.Plan.Commit
                      { first = [| k_word |]
                      ; recover = [||]
                      ; at_child = "x"
                      ; message = msg 1
                      ; hole = None
                      ; placeholder = n_hole
                      ; resume = None
                      ; body = Ir.Plan.Call 4
                      })
             }
           ; list_rule
           ; item
           ; paren
           ; { paren with
               name = "Empty"
             ; first = [||]
             ; body = Ir.Plan.Seq [| Ir.Plan.Open n_paren; Ir.Plan.Close |]
             }
          |]
      }
    , function
      | Plan.Check.Commit_matches_nothing _ -> true
      | _ -> false )
  ; ( "an optional word followed by a word"
    , with_body
        (open_
           (Ir.Plan.Seq
              [| Ir.Plan.Alt
                   { arms = [| [| k_word |], Ir.Plan.Bump |]
                   ; otherwise = Ir.Plan.Seq [||]
                   }
               ; expect k_word
              |]))
    , function
      | Plan.Check.Takes_what_follows _ -> true
      | _ -> false )
  ; ( "a list of words followed by a word"
    , with_body
        (open_
           (Ir.Plan.Seq
              [| Ir.Plan.Loop
                   { entry = 0
                   ; ends_on = None
                   ; states =
                       [| { accepts = [| [| k_word |], 0 |]
                          ; exit = Ir.Plan.May_exit
                          ; when_missing = None
                          ; emits = Ir.Plan.Bump
                          }
                       |]
                   }
               ; expect k_word
              |]))
    , function
      | Plan.Check.Takes_what_follows _ -> true
      | _ -> false )
  ; ( "a node opened and not closed"
    , with_body (Ir.Plan.Seq [| Ir.Plan.Open n_file; Ir.Plan.Bump |])
    , function
      | Plan.Check.Unbalanced _ -> true
      | _ -> false )
  ; ( "an alt's otherwise that opens a node and leaves it open"
    , with_body
        (open_
           (Ir.Plan.Alt
              { arms = [| [| k_word |], Ir.Plan.Bump |]; otherwise = Ir.Plan.Open n_file }))
    , function
      | Plan.Check.Unbalanced _ -> true
      | _ -> false )
  ; ( "a node closed before any was opened"
    , with_body (Ir.Plan.Seq [| Ir.Plan.Close; Ir.Plan.Open n_file |])
    , function
      | Plan.Check.Close_without_open _ -> true
      | _ -> false )
  ; ( "an infix operator on a kind below zero"
    , { good with blocks = [| { block with infix = [| -5, (10, 11) |] } |] }
    , function
      | Plan.Check.Negative_kind _ -> true
      | _ -> false )
  ; ( "a prefix operator on a kind below zero"
    , { good with blocks = [| { block with prefix = [| -5, 50 |] } |] }
    , function
      | Plan.Check.Negative_kind _ -> true
      | _ -> false )
  ; ( "delimiter pairs the wrong way round"
    , { good with pairs = [| k_lbrack, k_rbrack; k_lparen, k_rparen |] }
    , function
      | Plan.Check.Pairs_unordered _ -> true
      | _ -> false )
  ; ( "the same delimiter pair twice"
    , { good with
        pairs = [| k_lparen, k_rparen; k_lparen, k_rparen; k_lbrack, k_rbrack |]
      }
    , function
      | Plan.Check.Pairs_unordered _ -> true
      | _ -> false )
  ; ( "a delimiter pair on a kind below zero"
    , { good with pairs = [| -1, k_rparen; k_lbrack, k_rbrack |] }
    , function
      | Plan.Check.Negative_kind _ -> true
      | _ -> false )
  ]
;;

let () =
  let wrong = ref 0 in
  List.iter
    (fun (what, plan, is_it) ->
       match Plan.Check.run plan with
       | Ok () ->
         incr wrong;
         Law.fail "(c) check accepted %s" what
       | Error problems ->
         if not (List.exists is_it problems)
         then (
           incr wrong;
           Law.fail
             "(c) check reported the wrong thing about %s: %a"
             what
             (Format.pp_print_list
                ~pp_sep:(fun f () -> Format.fprintf f "; ")
                Plan.Check.pp_problem)
             problems))
    broken;
  if !wrong = 0
  then
    Law.pass
      "check reports each of %d broken plans with the right problem"
      (List.length broken)
;;

let () = Law.summarise "law_plan"
