(* -- the emitted lexer --------------------------------------------------------

      (a) A lex rebuilds its input, byte for byte, whatever the input.
      (b) Every token spans at least one byte, and its kind is a token kind
          the grammar has.
      (c) A token's text is in the language of the token it was taken as. No
          token's language holds a longer prefix from where it started, and
          no token declared earlier holds the same text. An error or
          unterminated token starts where no token's language holds any
          prefix at all.
      (d) A lexeme the input ended inside leaves as one unterminated token
          spanning those bytes.
      (e) The emitted lexer and test/lex agree, token for token.
      (f) Every emitted module is what the emitter writes now, byte for byte.

      Mechanism. Seven grammars, and for each of them a list of inputs
      written here. The emitted lexers are compiled and run: dune runs the
      generator, compiles what it wrote against lingo_runtime alone, and this
      links the result.

      Both shapes come out of one [Ocaml.Lexer] and both are checked. Parts
      (a) to (d) read the table, which {!Ocaml.Lexer.generate} emits by
      default. Part (e) reads the table and the match shape against test/lex,
      so both are held to one standard.

      Part (c)'s oracle is not a lexer. It evaluates each token's regex over
      the candidate text, so it says what the grammar's tokens denote with no
      automaton in between. A regex raises on malformed UTF-8 where the
      lexers decode it to U+FFFD, so a candidate that is not valid UTF-8 is
      counted and skipped, and the count prints.

      Part (e) is the differential, and its three sides reach the same tokens
      three ways. test/lex searches a state's interval list on every
      transition. The table maps the character to a class and indexes a row.
      The match shape branches on the byte. Anything lost in flattening the
      automaton, or in writing it out as control flow, shows up as a
      disagreement.

      Coverage. Thirteen grammars, 255 inputs, 2,674 tokens, two shapes, and
      the counts print beside the result. A law with no unterminated token and
      no error token to look at proves nothing about either, so both counts
      have to read above zero.

      What this says nothing about. What the parser makes of the tokens;
      test/laws/law_interp.ml reads that, over the same lexer. Nor which
      shape to emit, which test/bench/bench_lex.ml measures.

      What the match shape has that the table does not. The compiler reads the
      dispatch. A run that stops one character short of its range leaves the
      arms not covering the byte, and the exhaustiveness check says so before
      any test runs. The same edit to the table compiles and has to be caught
      by lexing something.

      Two gaps in the corpus, both above U+007F. Every non-ASCII input here is
      a guillemet, Greek or one emoji, and none of them sits at the top of a
      range its grammar names, so a run that ends one character short above
      U+007F changes nothing any of them lexes. The other gap closed: the
      inputs above U+007F were all characters their grammar had no token for,
      and a wrong class and no class stop the scan in the same place.
      unicode's "«©»" separates them, because U+00A9 is the first codepoint
      above the ASCII table and a search that starts one segment too high
      reads it as the character after it.

   -------------------------------------------------------------------------- *)

(* The record below is generated. assay derives a mutation from the emitter's
   code rather than from a sentence beside it, applies every one, and records
   what went red. Regenerate it with

     assay -config assay.conf -only ocaml

   Part (f) is what makes those mutants reachable at all: the two modules parts
   (a) to (e) run are compiled before the law starts, so without (f) every
   point in [Ocaml.Lexer] reads 0 killed whatever the tests do. That is what
   this record read on 2026-09-26, and the number said nothing about the tests.

   Four survivors, and each is a corpus that stops short rather than a test
   that does. They are in assay.findings with what they turn on. *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/ocaml/lexer.ml, 201 mutants, 197 killed, 4 survived.
        extreme     13  all killed, sexp_lexer.ml: 8 sexp_match.ml: 5
        sbr        169  all killed, sexp_lexer.ml: 125 sexp_match.ml: 33 json_match.ml: 9 sexp_lexer.mli: 2
        ror          7  4 killed, sexp_match.ml: 3 json_match.ml: 1; 3 survived
        aor          5  4 killed, sexp_lexer.ml: 4; 1 survived
        uoi          7  all killed, law_lex sexp_match.ml:: 3, law_lex sexp_lexer.ml:: 2, law_lex: 1, law_lex json_match.ml:: 1
      survived at lines 170 186 211 377
   ---------------------------------------------------------------------- *)

(* -- the corpus ------------------------------------------------------------ *)

type case =
  { name : string
  ; grammar : Core.Grammar.t
  ; lex : string -> Lingo_runtime.Token.t array (** The table shape. *)
  ; matched : string -> Lingo_runtime.Token.t array
    (** A function per state, dispatched by match. *)
  ; inputs : string list
  }

let corpus : case list =
  [ { name = "sexp"
    ; grammar = Lingo_grammars.Sexp_grammar.grammar
    ; lex = Emitted.Sexp_lexer.lex
    ; matched = Emitted.Sexp_match.lex
    ; inputs =
        [ ""
        ; "(a b)"
        ; "(a (b 12) c)"
        ; "( a  b )"
        ; "(a\n b)"
        ; "12.5 -3"
        ; "-1.5"
        ; "a-b"
        ; "<=>"
        ; "  )"
        ; "."
        ; "-."
        ; "(a ) b"
        ; "\xff"
        ; "(\xc3"
          (* Characters sexp has no token for, one two bytes wide and one
             three. An error token covers a whole character, and no other
             input here is wide enough to show it. *)
        ; "(\xc3\xa9)"
        ; "(a \xe2\x86\x92 b)"
        ]
    }
  ; { name = "json"
    ; grammar = Lingo_grammars.Json_grammar.grammar
    ; lex = Emitted.Json_lexer.lex
    ; matched = Emitted.Json_match.lex
    ; inputs =
        [ "{\"a\": 1}"
        ; "[1, 2]"
        ; "1e10"
        ; "-0.5E+3"
        ; "\"a\\\"b\""
        ; "true false null"
        ; "truer"
        ; "[1,]"
        ; "@"
        ; "0123" (* The next four end inside a lexeme, which part (d) reads. *)
        ; "\""
        ; "\"abc"
        ; "{\"a\": \"b\\"
        ; "[\"x\", \"y"
        ]
    }
  ; { name = "calc"
    ; grammar = Lingo_grammars.Calc_grammar.grammar
    ; lex = Emitted.Calc_lexer.lex
    ; matched = Emitted.Calc_match.lex
    ; inputs = [ "1+2*3"; "(1+2)*3"; "1 - 2"; "12/4"; "1+"; "$"; "1 2" ]
    }
  ; { name = "rassoc"
    ; grammar = Lingo_grammars.Rassoc_grammar.grammar
    ; lex = Emitted.Rassoc_lexer.lex
    ; matched = Emitted.Rassoc_match.lex
    ; inputs = [ "1^2^3"; "1+2+3"; "-1^2"; "1++"; "^"; "1^" ]
    }
  ; { name = "postfix"
    ; grammar = Lingo_grammars.Postfix_grammar.grammar
    ; lex = Emitted.Postfix_lexer.lex
    ; matched = Emitted.Postfix_match.lex
    ; inputs = [ "a.b[2]?+1"; "a(1, 2)"; "a{1}"; "a()"; "a."; "a[1"; "ab12"; "%" ]
    }
  ; { name = "shapes"
    ; grammar = Lingo_grammars.Shapes_grammar.grammar
    ; lex = Emitted.Shapes_lexer.lex
    ; matched = Emitted.Shapes_match.lex
    ; inputs =
        [ "let a"
        ; "let a = b, c"
        ; "{ let a; let b }"
        ; "{ let a end }"
          (* [let] and [end] are keywords and [name] takes the same letters.
             Part (c) checks both here: which token wins on equal text, and
             that no longer match was available. *)
        ; "letter"
        ; "lets end ending"
        ; "@ let a"
        ; "}"
        ; "#"
        ]
    }
  ; { name = "unicode"
    ; grammar = Lingo_grammars.Unicode_grammar.grammar
    ; lex = Emitted.Unicode_lexer.lex
    ; matched = Emitted.Unicode_match.lex
    ; inputs =
        [ "\xc2\xabhello\xc2\xbb"
        ; "\xc2\xab\xc3\xa9t\xc3\xa9\xc2\xbb"
        ; "\xc2\xab\xce\xb1\xce\xb2\xce\xb3\xc2\xbb"
        ; "\xc2\xaba \xe2\x86\x92 b\xc2\xbb"
        ; "\xc2\xab\xc2\xbb"
        ; "\xc2\xab$\xc2\xbb"
        ; "\xc2\xab"
        ; "\xe2\x86\x92"
          (* A truncated lead byte and a lone continuation byte. Both decode
             to U+FFFD, and the bytes still have to reach the stream. *)
        ; "\xc2"
        ; "\xab\xc2\xab"
          (* Hebrew is outside every range the grammar names and U+1F600 is
             past the basic plane, so the class search runs its full depth.
             U+00A9 is the first codepoint above the ASCII table, and a
             search that starts too high reads it as the character after
             it. *)
        ; "\xc2\xab\xd7\x90\xc2\xbb"
        ; "\xc2\xab\xf0\x9f\x98\x80\xc2\xbb"
        ; "\xc2\xab\xc2\xa9\xc2\xbb"
        ]
    }
    (* The six below take the shared list in test/inputs rather than a list
       here. The seven above predate it and hold bytes the shared list has no
       reason to carry: a truncated codepoint, a keyword prefix, a token that
       does not lex at all. *)
  ; { name = "recovery"
    ; grammar = Lingo_grammars.Recovery_grammar.grammar
    ; lex = Emitted.Recovery_lexer.lex
    ; matched = Emitted.Recovery_match.lex
    ; inputs = Inputs.all Inputs.recovery
    }
  ; { name = "comments"
    ; grammar = Lingo_grammars.Comments_grammar.grammar
    ; lex = Emitted.Comments_lexer.lex
    ; matched = Emitted.Comments_match.lex
    ; inputs = Inputs.all Inputs.comments
    }
  ; { name = "rust"
    ; grammar = Lingo_grammars.Rust_grammar.grammar
    ; lex = Emitted.Rust_lexer.lex
    ; matched = Emitted.Rust_match.lex
    ; inputs = Inputs.all Inputs.rust
    }
  ; { name = "effekt"
    ; grammar = Lingo_grammars.Effekt_grammar.grammar
    ; lex = Emitted.Effekt_lexer.lex
    ; matched = Emitted.Effekt_match.lex
    ; inputs = Inputs.all Inputs.effekt
    }
  ; { name = "wide"
    ; grammar = Lingo_grammars.Wide_grammar.grammar
    ; lex = Emitted.Wide_lexer.lex
    ; matched = Emitted.Wide_match.lex
    ; inputs = Inputs.all Inputs.wide
    }
  ; { name = "ml"
    ; grammar = Lingo_grammars.Ml_grammar.grammar
    ; lex = Emitted.Ml_lexer.lex
    ; matched = Emitted.Ml_match.lex
    ; inputs = Inputs.all Inputs.ml
    }
  ]
;;

(* -- counters -------------------------------------------------------------- *)

let inputs = ref 0
let tokens = ref 0
let extents = ref 0
let skipped = ref 0
let unterminated = ref 0
let errors = ref 0

(* -- the oracle ------------------------------------------------------------ *)

(* The token ids whose language holds [src.\[lo .. hi)]. [None] where those
   bytes are not valid UTF-8, which a regex refuses to read. *)
let holders (asts : Redfa.Ast.t array) (src : string) (lo : int) (hi : int)
  : int list option
  =
  let text = String.sub src lo (hi - lo) in
  if not (String.is_valid_utf_8 text)
  then None
  else (
    let out = ref [] in
    Array.iteri
      (fun (token_id : int) (ast : Redfa.Ast.t) ->
         if Redfa.Ast.eval ast text then out := token_id :: !out)
      asts;
    Some (List.rev !out))
;;

(* Whether any token's language holds a prefix from [lo] ending past [from]. *)
let longer (asts : Redfa.Ast.t array) (src : string) (lo : int) (from : int) : int option =
  let rec go hi =
    if hi > String.length src
    then None
    else (
      match holders asts src lo hi with
      | Some (_ :: _) -> Some hi
      | Some [] | None -> go (hi + 1))
  in
  go (from + 1)
;;

(* -- the parts ------------------------------------------------------------- *)

let show (src : string) : string =
  if String.length src > 24 then String.sub src 0 24 ^ "…" else src
;;

let part_a (name : string) (src : string) (ts : Lingo_runtime.Token.t array) : unit =
  let rebuilt = Array.fold_left (fun b (t : Lingo_runtime.Token.t) -> b ^ t.text) "" ts in
  if not (String.equal rebuilt src)
  then Law.fail "%s: %S rebuilds as %S" name (show src) (show rebuilt)
;;

let part_b
      (facts : Core.Facts.t)
      (name : string)
      (src : string)
      (ts : Lingo_runtime.Token.t array)
  : unit
  =
  Array.iter
    (fun (t : Lingo_runtime.Token.t) ->
       incr tokens;
       if String.length t.text = 0
       then Law.fail "%s: %S has an empty token" name (show src);
       let k = List.nth (Core.Kind.Table.kinds facts.kinds) t.kind in
       if
         Core.Facts.token_of_kind facts k = None
         && not
              (Core.Kind.equal k facts.error_token_kind
               || Core.Kind.equal k facts.unterminated_kind)
       then
         Law.fail
           "%s: %S holds kind %s"
           name
           (show src)
           (Core.Kind.Name.to_string (Core.Facts.kind_name facts k)))
    ts
;;

let part_c
      (facts : Core.Facts.t)
      (asts : Redfa.Ast.t array)
      (name : string)
      (src : string)
      (ts : Lingo_runtime.Token.t array)
  : unit
  =
  let lo = ref 0 in
  Array.iter
    (fun (t : Lingo_runtime.Token.t) ->
       let hi = !lo + String.length t.text in
       let kinds = Core.Kind.Table.kinds facts.kinds in
       let kind = List.nth kinds t.kind in
       (match holders asts src !lo hi with
        | None -> incr skipped
        | Some ids ->
          incr extents;
          (match Core.Facts.token_of_kind facts kind with
           | None ->
             (* An error or unterminated token: nothing matched from here. *)
             (match longer asts src !lo !lo with
              | None -> ()
              | Some e ->
                Law.fail
                  "%s: %S has no token at %d, and one ends at %d"
                  name
                  (show src)
                  !lo
                  e)
           | Some (def : Core.Token.def) ->
             if not (List.mem def.id ids)
             then
               Law.fail
                 "%s: %S takes %S as %s, which does not match it"
                 name
                 (show src)
                 t.text
                 (Core.Kind.Name.to_string (Core.Facts.kind_name facts kind));
             (match List.find_opt (fun (token_id : int) -> token_id < def.id) ids with
              | None -> ()
              | Some earlier ->
                Law.fail
                  "%s: %S takes %S as token %d, and token %d also holds it"
                  name
                  (show src)
                  t.text
                  def.id
                  earlier);
             (match longer asts src !lo hi with
              | None -> ()
              | Some e ->
                Law.fail
                  "%s: %S takes %d..%d, and a longer match ends at %d"
                  name
                  (show src)
                  !lo
                  hi
                  e)));
       lo := hi)
    ts
;;

let part_d
      (facts : Core.Facts.t)
      (name : string)
      (src : string)
      (ts : Lingo_runtime.Token.t array)
  : unit
  =
  Array.iteri
    (fun i (t : Lingo_runtime.Token.t) ->
       let kind = List.nth (Core.Kind.Table.kinds facts.kinds) t.kind in
       if Core.Kind.equal kind facts.error_token_kind then incr errors;
       if Core.Kind.equal kind facts.unterminated_kind
       then (
         incr unterminated;
         if i <> Array.length ts - 1
         then Law.fail "%s: %S continues past an unterminated token" name (show src)))
    ts
;;

let show_kinds (ts : Lingo_runtime.Token.t array) : string =
  String.concat
    " "
    (Array.to_list
       (Array.map
          (fun (t : Lingo_runtime.Token.t) -> Printf.sprintf "%d:%S" t.kind t.text)
          ts))
;;

let part_e
      (name : string)
      (shape : string)
      (src : string)
      (emitted : Lingo_runtime.Token.t array)
      (walked : Lingo_runtime.Token.t array)
  : unit
  =
  if
    Array.length emitted <> Array.length walked
    || not
         (Array.for_all2
            (fun (a : Lingo_runtime.Token.t) (b : Lingo_runtime.Token.t) ->
               a.kind = b.kind && String.equal a.text b.text)
            emitted
            walked)
  then
    Law.fail
      "%s/%s: %S lexes as [%s] here and [%s] over the automaton"
      name
      shape
      (show src)
      (show_kinds emitted)
      (show_kinds walked)
;;

(* Part (f) reads the module dune compiled and asks the emitter for it again.
   Everything above runs the lexer that module holds, which is built before the
   law starts, so nothing above can see a change in the emitter itself. This
   can: it calls {!Ocaml.Lexer.generate} in the law's own process. *)

let modules = ref 0

let part_f (file : string) (now : string) : unit =
  incr modules;
  Law.generated ~file now
;;

(* -- running --------------------------------------------------------------- *)

let () =
  List.iter
    (fun (case : case) ->
       match Core.Facts.of_grammar case.grammar with
       | Error errors ->
         List.iter
           (fun (error : Core.Error.t) -> Format.printf "%a@." Core.Error.pp error)
           errors;
         Law.fail "%s: the grammar does not check" case.name
       | Ok facts ->
         let asts =
           Array.map
             (fun (token : Core.Token.def) -> Redfa.Regex.to_ast token.regex)
             facts.tokens
         in
         let table = Core.Lexer.of_facts facts in
         Printf.printf
           "; %-8s states %d  classes %d  cells %d\n"
           case.name
           table.num_states
           table.num_classes
           (Array.length table.next);
         List.iter
           (fun (src : string) ->
              incr inputs;
              let emitted = case.lex src in
              let walked = Lex.run facts src in
              part_a case.name src emitted;
              part_b facts case.name src emitted;
              part_c facts asts case.name src emitted;
              part_d facts case.name src emitted;
              part_e case.name "table" src emitted walked;
              part_e case.name "match" src (case.matched src) walked)
           case.inputs;
         part_f (case.name ^ "_lexer.ml") (Ocaml.Emit.render (Ocaml.Lexer.generate facts));
         part_f
           (case.name ^ "_match.ml")
           (Ocaml.Emit.render (Ocaml.Lexer.generate ~shape:Match facts));
         part_f
           (case.name ^ "_lexer.mli")
           (Ocaml.Emit.render_signature Ocaml.Lexer.signature))
    corpus
;;

let () =
  if !unterminated = 0 then Law.fail "no input ended inside a lexeme";
  if !errors = 0 then Law.fail "no input held a character no token starts with";
  Law.pass
    "%d inputs, %d tokens, %d extents checked (%d skipped as malformed UTF-8)"
    !inputs
    !tokens
    !extents
    !skipped;
  Law.pass "%d unterminated tokens, %d error tokens" !unterminated !errors;
  Law.pass "%d emitted modules are what the emitter writes now" !modules;
  Law.exit_on_failure ()
;;
