(* -- the emitted residual tables ----------------------------------------------

      (a) The tables a grammar's module holds are the tables its plan gives.
      (b) The entry point over them gives the kinds a root starts with.
      (c) Every module the emitter wrote is what it writes now, byte for byte.

      Mechanism. Twelve grammars. For each, [Ir.Residual.Table.of_plan] is read
      off the plan here and compared with the literal the emitter wrote into
      the generated module, point for point.

      That is the whole of what generation has to get right. Whether those
      tables are the right tables is test/laws/law_residual part (h), which
      checks them against the interpreter at every byte of its corpus. Between
      the two, what a generated module gives is what the parse would take.

      The generated modules link [lingo_runtime] and nothing else, which the
      library stanza beside this enforces: one reaching for a plan would not
      build.

      What (b) reaches. A root's own first point is read before any transition
      runs, so a table whose transition targets are all wrong still gives the
      right set at the first byte. (b) is the entry point and nothing further
      in.

   -------------------------------------------------------------------------- *)

(* The record below is generated. assay derives a mutation from the emitter's
   code rather than from a sentence beside it, applies every one, and records
   what went red. Regenerate it with

     assay -config assay.conf -only ocaml

   Part (c) is what makes those mutants reachable at all: the module this law
   reads is compiled before the law starts, so without (c) every point in
   [Ocaml.Residual] reads 0 killed whatever the tests do. *)

(* -- mutation testing, generated by assay on 2026-10-02 ---------------------
      lib/ocaml/residual.ml, 23 mutants, 23 killed.
        extreme      2  all killed, sexp_residual.ml: 1 sexp_residual.mli: 1
        sbr         20  all killed, sexp_residual.ml: 17 sexp_residual.mli: 3
        aor          1  all killed, law_ahead: 1
   ---------------------------------------------------------------------- *)

open StdLabels

type case =
  { name : string
  ; grammar : Core.Grammar.t
  ; tables : Lingo_runtime.Ahead.t
  ; source : string
  }

let corpus =
  [ { name = "sexp"
    ; grammar = Lingo_grammars.Sexp_grammar.grammar
    ; tables = Emitted_parsers.Sexp_residual.tables
    ; source = "(a b)"
    }
  ; { name = "json"
    ; grammar = Lingo_grammars.Json_grammar.grammar
    ; tables = Emitted_parsers.Json_residual.tables
    ; source = "[1, 2]"
    }
  ; { name = "calc"
    ; grammar = Lingo_grammars.Calc_grammar.grammar
    ; tables = Emitted_parsers.Calc_residual.tables
    ; source = "1+2*3"
    }
  ; { name = "rassoc"
    ; grammar = Lingo_grammars.Rassoc_grammar.grammar
    ; tables = Emitted_parsers.Rassoc_residual.tables
    ; source = "1^2^3"
    }
  ; { name = "postfix"
    ; grammar = Lingo_grammars.Postfix_grammar.grammar
    ; tables = Emitted_parsers.Postfix_residual.tables
    ; source = "a(1, 2)"
    }
  ; { name = "shapes"
    ; grammar = Lingo_grammars.Shapes_grammar.grammar
    ; tables = Emitted_parsers.Shapes_residual.tables
    ; source = "let a = b"
    }
  ; { name = "unicode"
    ; grammar = Lingo_grammars.Unicode_grammar.grammar
    ; tables = Emitted_parsers.Unicode_residual.tables
    ; source = "\xc2\xabhello\xc2\xbb"
    }
  ; { name = "recovery"
    ; grammar = Lingo_grammars.Recovery_grammar.grammar
    ; tables = Emitted_parsers.Recovery_residual.tables
    ; source = "let a in end"
    }
  ; { name = "rust"
    ; grammar = Lingo_grammars.Rust_grammar.grammar
    ; tables = Emitted_parsers.Rust_residual.tables
    ; source = "fn f(a: int) -> int { let x = 1; }"
    }
  ; { name = "comments"
    ; grammar = Lingo_grammars.Comments_grammar.grammar
    ; tables = Emitted_parsers.Comments_residual.tables
    ; source = "[a /* mid */, b]"
    }
  ; { name = "effekt"
    ; grammar = Lingo_grammars.Effekt_grammar.grammar
    ; tables = Emitted_parsers.Effekt_residual.tables
    ; source = "def f(x: Int): Int = x;"
    }
  ; { name = "wide"
    ; grammar = Lingo_grammars.Wide_grammar.grammar
    ; tables = Emitted_parsers.Wide_residual.tables
    ; source = "select a from t where a > 10;"
    }
  ; { name = "ml"
    ; grammar = Lingo_grammars.Ml_grammar.grammar
    ; tables = Emitted_parsers.Ml_residual.tables
    ; source = "let f (a : int) : int = a + 1;"
    }
  ]
;;

let points = ref 0

let () =
  List.iter corpus ~f:(fun c ->
    match Core.Facts.of_grammar c.grammar with
    | Error _ -> Law.fail "%s: the grammar does not check" c.name
    | Ok facts ->
      let plan, _ = Plan.Lower.of_facts facts in
      let entries = Ir.Residual.Table.of_plan plan in
      let from_plan = Array.of_list (List.map entries ~f:snd) in
      Array.iter from_plan ~f:(fun table -> points := !points + Array.length table);
      if c.tables.points <> from_plan
      then
        Law.fail
          "(a) %s emitted %d automata and its plan gives %d, or their points differ"
          c.name
          (Array.length c.tables.points)
          (Array.length from_plan);
      List.iteri entries ~f:(fun index (kind, _) ->
        if kind >= Array.length c.tables.of_kind || c.tables.of_kind.(kind) <> index
        then Law.fail "(a) %s sends kind %d to the wrong automaton" c.name kind);
      if c.tables.trivia <> plan.Ir.Plan.trivia
      then Law.fail "(a) %s emitted the wrong trivia kinds" c.name;
      if c.tables.error_kind <> plan.Ir.Plan.error_kind
      then Law.fail "(a) %s emitted the wrong error kind" c.name)
;;

let () =
  if Law.failures () = 0
  then Law.pass "every emitted table is the one its plan gives, over %d points" !points
;;

(* -- (b) the entry point ---------------------------------------------------- *)

(* At the first byte nothing has been read, so what may appear is what the root
   starts with. The plan already carries that set, worked out by a different
   route. *)
let () =
  let before = Law.failures () in
  List.iter corpus ~f:(fun c ->
    match Core.Facts.of_grammar c.grammar with
    | Error _ -> ()
    | Ok facts ->
      let plan, _ = Plan.Lower.of_facts facts in
      let root, _ = Interp.run plan plan.Ir.Plan.roots.(0) (Lex.run facts c.source) in
      let given = Lingo_runtime.Ahead.at c.tables root ~offset:0 in
      let first = plan.Ir.Plan.rules.(plan.Ir.Plan.roots.(0)).first in
      if given <> first
      then
        Law.fail
          "(b) %s gives %s at the first byte, where its root starts with %s"
          c.name
          (String.concat ~sep:" " (List.map (Array.to_list given) ~f:string_of_int))
          (String.concat ~sep:" " (List.map (Array.to_list first) ~f:string_of_int)));
  if Law.failures () = before
  then
    Law.pass
      "the entry point gives what the root starts with, over %d grammars"
      (List.length corpus)
;;

(* -- (c) the emitter ------------------------------------------------------- *)

(* Parts (a) and (b) read the tables the emitted module holds, and that module
   is compiled before the law starts: nothing either part does can see a change
   in {!Ocaml.Residual}, which wrote it. This can, because the emitter runs
   here and the bytes it writes now are compared with the bytes on disk. *)
let () =
  let before = Law.failures () in
  let modules = ref 0 in
  List.iter corpus ~f:(fun c ->
    match Core.Facts.of_grammar c.grammar with
    | Error _ -> ()
    | Ok facts ->
      let plan, _ = Plan.Lower.of_facts facts in
      modules := !modules + 2;
      Law.generated
        ~file:(c.name ^ "_residual.ml")
        (Ocaml.Emit.render (Ocaml.Residual.generate plan));
      Law.generated
        ~file:(c.name ^ "_residual.mli")
        (Ocaml.Emit.render_signature (Ocaml.Residual.signature plan)));
  if Law.failures () = before
  then Law.pass "%d emitted modules are what the emitter writes now" !modules
;;

let () = Law.summarise "law_ahead"
