(* -- the emitted views ---------------------------------------------------------

      (a) The walk accounts for every child of every node. A child no slot
          takes is trivia, an error node, a token the lexer could not finish
          or classify, one of the frame's own tokens (its opener, its closer,
          its separator), or input a diagnostic reported as extra.
      (b) A placeholder fills the slot the parse was filling when it left it.
      (c) Every module the emitter wrote is what it writes now, byte for byte.
      (d) The slots are filled in order: a later child is never in an earlier
          slot, and a child that does not repeat holds one node at most.
      (e) Every type, module and constructor the views module defines is a
          manifest entry in the scope it lands in, and so is every accessor
          of a production's module. A name the manifest does not list is a
          name no collision check has seen.

      Mechanism. Fourteen grammars, and three corpora over each: the inputs in
      test/inputs, [Sweep]'s damaged copies of them, and draws from the
      grammar. The interpreter parses each one, and every node the result
      holds is walked by the emitted [Slots.slots].

      Part (b) has an oracle of its own. A placeholder's payload is the id of
      its [Missing] diagnostic, and that diagnostic names the child the parse
      was filling. The walk never reads a diagnostic, so the two agree only
      where the walk put the placeholder where the parse did.

      Two [Missing] reports over one range fold into one entry, which keeps the
      first one's child name. So (b) reads a placeholder only where its id
      first appears in source order, and only where the child its diagnostic names
      is one that takes a placeholder. A required token takes none, and a
      placeholder folded into a token's report names the token.

      test/views_emit/nested is the fourteenth, and it is here for the views
      alone. Its block has no token atom, so no base node, and one child's
      variant holds a block's position as an arm. No other grammar has either.

      Part (e) reads the emitted structure rather than the source text, so a
      name is classified by where it is defined. It is the cross-check
      test/laws/law_manifest.ml's header asks for, for this one emitter.

      What this says nothing about. Whether an accessor reads its slot right:
      which arm of a variant a node becomes, and that a placeholder reads as
      [None]. test/views_emit/test_views.ml reads those, through the typed
      modules, on inputs chosen for them.
   -------------------------------------------------------------------------- *)

(* The record below is generated. assay derives a mutation from the emitter's
   code rather than from a sentence beside it, applies every one, and records
   what went red. Regenerate it with

     assay -config assay.conf -only ocaml

   Part (c) is what makes those mutants reachable at all, for the reason
   test/parse_emit/law_parse.ml gives for its part (e).

   Every mutant dies. The four that time out drop the walk's step to the next
   slot, and the law hangs.

   Seven survived before test/views_emit/nested went in. Two gave a block with
   no token atom a base view, and five were the arm that holds a block's
   position. No grammar had either shape, and the nested grammar has both. *)

(* -- mutation testing, generated by assay on 2026-10-03 ---------------------
      lib/ocaml/views.ml, 183 mutants, 179 killed, 4 timed out.
        extreme     16  all killed, law_views sexp_views.ml:: 7, law_views calc_views.ml:: 5, law_views (e): 2, law_views: 1, law_views sexp_views.mli:: 1
        sbr        148  144 killed, law_views sexp_views.ml:: 129, law_views nested_views.ml:: 7, law_views sexp_views.mli:: 4, law_views calc_views.ml:: 2, law_views: 1, law_views calc_views.mli:: 1; 4 timed out
        ror          7  all killed, sexp_views.ml: 4 (e) 2 calc_views.ml: 1
        uoi         12  all killed, law_views sexp_views.ml:: 7, law_views: 2, law_views calc_views.ml:: 2, law_views sexp_views.mli:: 1
   ---------------------------------------------------------------------- *)

type case =
  { name : string
  ; grammar : Core.Grammar.t
  ; slots : Siesta.Syntax.t -> Siesta.Syntax.elem list array option
  ; seeds : string list
  }

let corpus : case list =
  [ { name = "sexp"
    ; grammar = Lingo_grammars.Sexp_grammar.grammar
    ; slots = Emitted_slots.Sexp_slots.Slots.slots
    ; seeds = Inputs.all Inputs.sexp
    }
  ; { name = "json"
    ; grammar = Lingo_grammars.Json_grammar.grammar
    ; slots = Emitted_slots.Json_slots.Slots.slots
    ; seeds = Inputs.all Inputs.json
    }
  ; { name = "calc"
    ; grammar = Lingo_grammars.Calc_grammar.grammar
    ; slots = Emitted_slots.Calc_slots.Slots.slots
    ; seeds = Inputs.all Inputs.calc
    }
  ; { name = "rassoc"
    ; grammar = Lingo_grammars.Rassoc_grammar.grammar
    ; slots = Emitted_slots.Rassoc_slots.Slots.slots
    ; seeds = Inputs.all Inputs.rassoc
    }
  ; { name = "postfix"
    ; grammar = Lingo_grammars.Postfix_grammar.grammar
    ; slots = Emitted_slots.Postfix_slots.Slots.slots
    ; seeds = Inputs.all Inputs.postfix
    }
  ; { name = "shapes"
    ; grammar = Lingo_grammars.Shapes_grammar.grammar
    ; slots = Emitted_slots.Shapes_slots.Slots.slots
    ; seeds = Inputs.all Inputs.shapes
    }
  ; { name = "unicode"
    ; grammar = Lingo_grammars.Unicode_grammar.grammar
    ; slots = Emitted_slots.Unicode_slots.Slots.slots
    ; seeds = Inputs.all Inputs.unicode
    }
  ; { name = "recovery"
    ; grammar = Lingo_grammars.Recovery_grammar.grammar
    ; slots = Emitted_slots.Recovery_slots.Slots.slots
    ; seeds = Inputs.all Inputs.recovery
    }
  ; { name = "comments"
    ; grammar = Lingo_grammars.Comments_grammar.grammar
    ; slots = Emitted_slots.Comments_slots.Slots.slots
    ; seeds = Inputs.all Inputs.comments
    }
  ; { name = "rust"
    ; grammar = Lingo_grammars.Rust_grammar.grammar
    ; slots = Emitted_slots.Rust_slots.Slots.slots
    ; seeds = Inputs.all Inputs.rust
    }
  ; { name = "effekt"
    ; grammar = Lingo_grammars.Effekt_grammar.grammar
    ; slots = Emitted_slots.Effekt_slots.Slots.slots
    ; seeds = Inputs.all Inputs.effekt
    }
  ; { name = "wide"
    ; grammar = Lingo_grammars.Wide_grammar.grammar
    ; slots = Emitted_slots.Wide_slots.Slots.slots
    ; seeds = Inputs.all Inputs.wide
    }
  ; { name = "ml"
    ; grammar = Lingo_grammars.Ml_grammar.grammar
    ; slots = Emitted_slots.Ml_slots.Slots.slots
    ; seeds = Inputs.all Inputs.ml
    }
  ; { name = "nested"
    ; grammar = Nested_grammar.grammar
    ; slots = Emitted_slots.Nested_slots.Slots.slots
    ; seeds = Nested_grammar.good @ Nested_grammar.broken
    }
  ]
;;

(* The same draw test/parse_emit/law_parse.ml takes, so the two laws read the
   same corpus. *)
let drawn_per_grammar = 500
let drawn_seed = [| 0x1EA5; 0x100 |]

let drawn (name : string) (facts : Core.Facts.t) : string list =
  match Fuzz.Harness.make ~lex:(Lex.run facts) ~name facts with
  | exception e ->
    Law.fail "%s: no harness to draw from (%s)" name (Printexc.to_string e);
    []
  | harness ->
    let rng = Random.State.make drawn_seed in
    List.init drawn_per_grammar (fun _ ->
      Fuzz.Harness.decode harness (Fuzz.Harness.draw harness rng))
;;

(* -- counts ----------------------------------------------------------------- *)

let inputs = ref 0
let nodes = ref 0
let placed = ref 0
let left_out = ref 0
let placeholders = ref 0
let modules = ref 0

(* The first few failures of each part, so a run that fails prints where. *)
let shown : (string, int) Hashtbl.t = Hashtbl.create 4

let fail_at (part : string) (fmt : ('a, Format.formatter, unit, unit) format4) : 'a =
  let n = Option.value (Hashtbl.find_opt shown part) ~default:0 in
  Hashtbl.replace shown part (n + 1);
  if n < 5 then Law.fail fmt else Format.ifprintf Format.std_formatter fmt
;;

let show (src : string) : string =
  if String.length src > 40 then String.sub src 0 40 ^ "\xe2\x80\xa6" else src
;;

(* -- one node --------------------------------------------------------------- *)

let index_of (elem : Siesta.Syntax.elem) : int =
  match elem with
  | Siesta.Syntax.Node n -> Siesta.Syntax.index_in_parent n
  | Siesta.Syntax.Token t -> Siesta.Syntax.Token.index_in_parent t
;;

(* What a node of this rule may hold outside its slots. *)
let ignorable (facts : Core.Facts.t) (plan : Ir.Plan.t) (d : Core.Rule.def) (k : int)
  : bool
  =
  let kind = Core.Kind.to_int in
  let frame =
    match d.frame with
    | Core.Rule.Delimited { open_; close; sep; _ } ->
      kind open_
      :: kind close
      :: Option.to_list (Option.map (fun s -> kind s.Core.Rule.sep_tok) sep)
    | Core.Rule.Separated { sep_tok; _ } -> [ kind sep_tok ]
    | Core.Rule.Plain | Core.Rule.Committed _ -> []
  in
  List.mem k frame
  || Array.mem k plan.trivia
  || k = kind facts.error_kind
  || k = kind facts.error_token_kind
  || k = kind facts.unterminated_kind
;;

(* Whether a diagnostic covers the child. The root's [Drain] sweeps what is
   left of the input into the root itself, and reports it. *)
let reported (diagnostics : Lingo_runtime.Diagnostic.t array) (elem : Siesta.Syntax.elem)
  : bool
  =
  let lo, hi = Siesta.Syntax.elem_text_range elem in
  Array.exists
    (fun (d : Lingo_runtime.Diagnostic.t) ->
       match d.kind with
       | Lingo_runtime.Diagnostic.Extra _ | Lingo_runtime.Diagnostic.Unexpected ->
         let dlo, dhi = d.range in
         dlo <= lo && hi <= dhi
       | Lingo_runtime.Diagnostic.Missing _ -> false)
    diagnostics
;;

let is_placeholder (facts : Core.Facts.t) (k : int) : bool =
  k = Core.Kind.to_int facts.missing_kind
  || Array.exists
       (fun (d : Core.Rule.def) ->
          match d.hole with
          | Some h -> Core.Kind.to_int h = k
          | None -> false)
       facts.rules
;;

(* Whether the child takes a placeholder: a required child that is not one
   token. *)
let takes_placeholder (facts : Core.Facts.t) (c : Core.Rule.child) : bool =
  match c.modifier, c.alts with
  | (Core.Grammar.Exactly_one | Core.Grammar.One_or_more _), [| k |] ->
    not (Core.Facts.is_token_kind facts k)
  | (Core.Grammar.Exactly_one | Core.Grammar.One_or_more _), _ -> true
  | (Core.Grammar.Zero_or_one | Core.Grammar.Zero_or_more _), _ -> false
;;

let repeats (c : Core.Rule.child) : bool =
  match c.modifier with
  | Core.Grammar.Zero_or_more _ | Core.Grammar.One_or_more _ -> true
  | Core.Grammar.Exactly_one | Core.Grammar.Zero_or_one -> false
;;

let check_node
      (case : case)
      (facts : Core.Facts.t)
      (plan : Ir.Plan.t)
      (diagnostics : Lingo_runtime.Diagnostic.t array)
      (first : (int, int * int) Hashtbl.t)
      (number : int)
      (src : string)
      (node : Siesta.Syntax.t)
  : unit
  =
  let rule = facts.kind_rule.(Siesta.Syntax.kind node) in
  match case.slots node with
  | None -> ()
  | Some _ when rule < 0 -> fail_at "a" "(a) %s: a view for a kind with no rule" case.name
  | Some slots ->
    let d = facts.rules.(rule) in
    incr nodes;
    let children = Siesta.Syntax.children_array node in
    let slot_of = Array.make (Array.length children) (-1) in
    Array.iteri
      (fun slot elems ->
         List.iter
           (fun elem ->
              incr placed;
              slot_of.(index_of elem) <- slot)
           elems)
      slots;
    (* (d) *)
    Array.iteri
      (fun slot elems ->
         match elems with
         | _ :: _ :: _ when not (repeats d.children.(slot)) ->
           fail_at
             "d"
             "(d) %s %S: %s holds %d nodes in %s, which does not repeat"
             case.name
             (show src)
             (Core.Grammar.Name.Rule.to_string d.name)
             (List.length elems)
             (Core.Grammar.Name.Child.to_string d.children.(slot).child_name)
         | _ -> ())
      slots;
    ignore
      (Array.fold_left
         (fun last slot ->
            if slot < 0
            then last
            else (
              if slot < last
              then
                fail_at
                  "d"
                  "(d) %s %S: %s fills slot %d after slot %d"
                  case.name
                  (show src)
                  (Core.Grammar.Name.Rule.to_string d.name)
                  slot
                  last;
              slot))
         (-1)
         slot_of);
    Array.iteri
      (fun i elem ->
         let k = Siesta.Syntax.elem_kind elem in
         (* (a) *)
         if slot_of.(i) < 0
         then (
           incr left_out;
           if not (ignorable facts plan d k || reported diagnostics elem)
           then
             fail_at
               "a"
               "(a) %s %S: %s left child %d of kind %d in no slot"
               case.name
               (show src)
               (Core.Grammar.Name.Rule.to_string d.name)
               i
               k);
         (* (b) *)
         match elem with
         | Siesta.Syntax.Token _ -> ()
         | Siesta.Syntax.Node n ->
           let id = Siesta.Green.payload (Siesta.Syntax.green n) in
           if
             id > 0
             && is_placeholder facts k
             && Hashtbl.find_opt first id = Some (number, i)
           then (
             match diagnostics.(id - 1).kind with
             | Lingo_runtime.Diagnostic.Missing { at_child = Some name; _ } ->
               let named =
                 Array.find_index
                   (fun (c : Core.Rule.child) ->
                      Core.Grammar.Name.Child.to_string c.child_name = name)
                   d.children
               in
               (match named with
                | Some j when takes_placeholder facts d.children.(j) ->
                  incr placeholders;
                  if slot_of.(i) <> j
                  then
                    fail_at
                      "b"
                      "(b) %s %S: %s's placeholder for %s is in slot %d"
                      case.name
                      (show src)
                      (Core.Grammar.Name.Rule.to_string d.name)
                      name
                      slot_of.(i)
                | Some _ | None -> ())
             | Lingo_runtime.Diagnostic.Missing { at_child = None; _ }
             | Lingo_runtime.Diagnostic.Extra _ | Lingo_runtime.Diagnostic.Unexpected ->
               ()))
      children
;;

(* -- (e) ---------------------------------------------------------------------- *)

let manifest_misses = ref 0
let names_checked = ref 0

let listed (facts : Core.Facts.t) (scope : Core.Manifest.Scope.t) (name : string) : bool =
  List.exists
    (fun (e : Core.Manifest.entry) ->
       e.scope = scope && Core.Manifest.to_string e.emitted = name)
    (Core.Manifest.entries facts.names)
;;

let has_accessors (facts : Core.Facts.t) (m : string) : bool =
  List.exists
    (fun (e : Core.Manifest.entry) -> e.scope = Core.Manifest.Scope.View_accessor m)
    (Core.Manifest.entries facts.names)
;;

let expect
      (case : case)
      (facts : Core.Facts.t)
      (scope : Core.Manifest.Scope.t)
      (name : string)
  : unit
  =
  incr names_checked;
  if not (listed facts scope name)
  then (
    incr manifest_misses;
    fail_at
      "e"
      "(e) %s: the views module defines %S, and the manifest has no %s of that name"
      case.name
      name
      (Core.Manifest.Scope.name scope))
;;

let check_manifest (case : case) (facts : Core.Facts.t) : unit =
  List.iter
    (fun (item : Ppxlib.structure_item) ->
       match item.pstr_desc with
       | Pstr_type (_, decls) ->
         List.iter
           (fun (d : Ppxlib.type_declaration) ->
              expect case facts Core.Manifest.Scope.View_type d.ptype_name.txt;
              match d.ptype_kind with
              | Ptype_variant ctors ->
                List.iter
                  (fun (c : Ppxlib.constructor_declaration) ->
                     expect
                       case
                       facts
                       (Core.Manifest.Scope.View_constructor d.ptype_name.txt)
                       c.pcd_name.txt)
                  ctors
              | Ptype_abstract | Ptype_record _ | Ptype_open -> ())
           decls
       | Pstr_module { pmb_name = { txt = Some m; _ }; pmb_expr; _ } ->
         expect case facts Core.Manifest.Scope.View_module m;
         if has_accessors facts m
         then (
           match pmb_expr.pmod_desc with
           | Pmod_structure items ->
             List.iter
               (fun (inner : Ppxlib.structure_item) ->
                  match inner.pstr_desc with
                  | Pstr_value (_, bindings) ->
                    List.iter
                      (fun (b : Ppxlib.value_binding) ->
                         match b.pvb_pat.ppat_desc with
                         | Ppat_var { txt; _ } ->
                           expect case facts (Core.Manifest.Scope.View_accessor m) txt
                         | _ -> ())
                      bindings
                  | _ -> ())
               items
           | _ -> ())
       | _ -> ())
    (Ocaml.Views.generate facts)
;;

let run_one (case : case) (facts : Core.Facts.t) (plan : Ir.Plan.t) (src : string) : unit =
  incr inputs;
  let green, diagnostics = Interp.run plan plan.roots.(0) (Lex.run facts src) in
  let diagnostics = Array.of_list diagnostics in
  (* Where each placeholder's id first appears in source order, as a node's
     number and a child's index. Both walks number the nodes in the same
     order. Missing children at the end of the input share one id, and the
     source order puts an inner node's placeholders before the ones its
     parent holds after it. *)
  let first = Hashtbl.create 8 in
  let count = ref 0 in
  let rec mark (node : Siesta.Syntax.t) =
    let number = !count in
    incr count;
    Array.iteri
      (fun i elem ->
         match elem with
         | Siesta.Syntax.Node n ->
           let id = Siesta.Green.payload (Siesta.Syntax.green n) in
           if
             id > 0
             && is_placeholder facts (Siesta.Syntax.elem_kind elem)
             && not (Hashtbl.mem first id)
           then Hashtbl.replace first id (number, i);
           mark n
         | Siesta.Syntax.Token _ -> ())
      (Siesta.Syntax.children_array node)
  in
  let root = Siesta.Syntax.of_root green in
  mark root;
  count := 0;
  let rec go (node : Siesta.Syntax.t) =
    let number = !count in
    incr count;
    check_node case facts plan diagnostics first number src node;
    Array.iter
      (function
        | Siesta.Syntax.Node n -> go n
        | Siesta.Syntax.Token _ -> ())
      (Siesta.Syntax.children_array node)
  in
  go root
;;

let () =
  List.iter
    (fun (case : case) ->
       match Core.Facts.of_grammar case.grammar with
       | Error _ -> Law.fail "%s: the grammar does not check" case.name
       | Ok facts ->
         let plan, _ = Plan.Lower.of_facts facts in
         List.iter
           (run_one case facts plan)
           (case.seeds @ Sweep.inputs facts case.seeds @ drawn case.name facts);
         check_manifest case facts;
         modules := !modules + 2;
         Law.generated
           ~file:(case.name ^ "_views.ml")
           (Ocaml.Emit.render (Ocaml.Views.generate facts));
         Law.generated
           ~file:(case.name ^ "_views.mli")
           (Ocaml.Emit.render_signature (Ocaml.Views.signature facts)))
    corpus
;;

let () =
  if not (Hashtbl.mem shown "a")
  then
    Law.pass
      "(a) the walk accounts for every child, over %d inputs and %d nodes (%d placed, %d \
       left out)"
      !inputs
      !nodes
      !placed
      !left_out;
  if not (Hashtbl.mem shown "b")
  then
    Law.pass
      "(b) every placeholder fills the slot its diagnostic names, over %d placeholders"
      !placeholders;
  if !placeholders = 0 then Law.fail "(b) no input left a placeholder to read";
  Law.pass "(c) %d emitted modules are what the emitter writes now" !modules;
  if not (Hashtbl.mem shown "d")
  then Law.pass "(d) every node's slots are filled in order, over %d nodes" !nodes;
  if !manifest_misses = 0
  then
    Law.pass
      "(e) every name the views module defines is a manifest entry, over %d names"
      !names_checked;
  Law.exit_on_failure ()
;;
